// WARNING: Please don't edit this file. It was generated by C++/WinRT v3.0.260715.1

void* winrt_make_CommunityToolkit_Maui_Media_WinRT_DrmLicenseAcquiredEventArgs()
{
    return winrt::detach_abi(winrt::make<winrt::CommunityToolkit::Maui::Media::WinRT::factory_implementation::DrmLicenseAcquiredEventArgs>());
}
WINRT_EXPORT namespace winrt::CommunityToolkit::Maui::Media::WinRT
{
    DrmLicenseAcquiredEventArgs::DrmLicenseAcquiredEventArgs(bool success, param::hstring const& errorMessage) :
        DrmLicenseAcquiredEventArgs(make<CommunityToolkit::Maui::Media::WinRT::implementation::DrmLicenseAcquiredEventArgs>(success, errorMessage))
    {
    }
}
