// WARNING: Please don't edit this file. It was generated by C++/WinRT v3.0.260715.1

#pragma once
#ifdef WINRT_IMPORT_MODULE
#include "winrt/base_macros.h"
import winrt.CommunityToolkit.Maui.Media.WinRT;
#else // WINRT_IMPORT_MODULE
#include "winrt/CommunityToolkit.Maui.Media.WinRT.h"
#endif // WINRT_IMPORT_MODULE
namespace winrt::CommunityToolkit::Maui::Media::WinRT::implementation
{
    template <typename D, typename... I>
    struct WINRT_IMPL_EMPTY_BASES MediaEngineSizeChangedEventArgs_base : implements<D, CommunityToolkit::Maui::Media::WinRT::MediaEngineSizeChangedEventArgs, I...>
    {
        using base_type = MediaEngineSizeChangedEventArgs_base;
        using class_type = CommunityToolkit::Maui::Media::WinRT::MediaEngineSizeChangedEventArgs;
        using implements_type = typename MediaEngineSizeChangedEventArgs_base::implements_type;
        using implements_type::implements_type;
        
        hstring GetRuntimeClassName() const override
        {
            return L"CommunityToolkit.Maui.Media.WinRT.MediaEngineSizeChangedEventArgs";
        }
    };
}
namespace winrt::CommunityToolkit::Maui::Media::WinRT::factory_implementation
{
    template <typename D, typename T, typename... I>
    struct WINRT_IMPL_EMPTY_BASES MediaEngineSizeChangedEventArgsT : implements<D, winrt::Windows::Foundation::IActivationFactory, winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineSizeChangedEventArgsFactory, I...>
    {
        using instance_type = CommunityToolkit::Maui::Media::WinRT::MediaEngineSizeChangedEventArgs;

        hstring GetRuntimeClassName() const
        {
            return L"CommunityToolkit.Maui.Media.WinRT.MediaEngineSizeChangedEventArgs";
        }
        auto CreateInstance(std::uint32_t width, std::uint32_t height)
        {
            return make<T>(width, height);
        }
        [[noreturn]] winrt::Windows::Foundation::IInspectable ActivateInstance() const
        {
            throw hresult_not_implemented();
        }
    };
}

#if defined(WINRT_FORCE_INCLUDE_MEDIAENGINESIZECHANGEDEVENTARGS_XAML_G_H) || __has_include("MediaEngineSizeChangedEventArgs.xaml.g.h")

#include "MediaEngineSizeChangedEventArgs.xaml.g.h"

#else

namespace winrt::CommunityToolkit::Maui::Media::WinRT::implementation
{
    template <typename D, typename... I>
    using MediaEngineSizeChangedEventArgsT = MediaEngineSizeChangedEventArgs_base<D, I...>;
}

#endif
