// WARNING: Please don't edit this file. It was generated by C++/WinRT v3.0.260715.1

void* winrt_make_CommunityToolkit_Maui_Media_WinRT_MediaEngineStateChangedEventArgs()
{
    return winrt::detach_abi(winrt::make<winrt::CommunityToolkit::Maui::Media::WinRT::factory_implementation::MediaEngineStateChangedEventArgs>());
}
WINRT_EXPORT namespace winrt::CommunityToolkit::Maui::Media::WinRT
{
    MediaEngineStateChangedEventArgs::MediaEngineStateChangedEventArgs(std::int32_t oldState, std::int32_t newState) :
        MediaEngineStateChangedEventArgs(make<CommunityToolkit::Maui::Media::WinRT::implementation::MediaEngineStateChangedEventArgs>(oldState, newState))
    {
    }
}
