// WARNING: Please don't edit this file. It was generated by C++/WinRT v3.0.260715.1

void* winrt_make_CommunityToolkit_Maui_Media_WinRT_MediaEngineTimeChangedEventArgs()
{
    return winrt::detach_abi(winrt::make<winrt::CommunityToolkit::Maui::Media::WinRT::factory_implementation::MediaEngineTimeChangedEventArgs>());
}
WINRT_EXPORT namespace winrt::CommunityToolkit::Maui::Media::WinRT
{
    MediaEngineTimeChangedEventArgs::MediaEngineTimeChangedEventArgs(double positionSeconds, double durationSeconds) :
        MediaEngineTimeChangedEventArgs(make<CommunityToolkit::Maui::Media::WinRT::implementation::MediaEngineTimeChangedEventArgs>(positionSeconds, durationSeconds))
    {
    }
}
