// WARNING: Please don't edit this file. It was generated by C++/WinRT v3.0.260715.1

#pragma once
#ifdef WINRT_IMPORT_MODULE
#include "winrt/base_macros.h"
import winrt.CommunityToolkit.Maui.Media.WinRT;
#else // WINRT_IMPORT_MODULE
#include "winrt/CommunityToolkit.Maui.Media.WinRT.h"
#endif // WINRT_IMPORT_MODULE
namespace winrt::CommunityToolkit::Maui::Media::WinRT::implementation
{
    template <typename D, typename... I>
    struct WINRT_IMPL_EMPTY_BASES MediaEngineStateChangedEventArgs_base : implements<D, CommunityToolkit::Maui::Media::WinRT::MediaEngineStateChangedEventArgs, I...>
    {
        using base_type = MediaEngineStateChangedEventArgs_base;
        using class_type = CommunityToolkit::Maui::Media::WinRT::MediaEngineStateChangedEventArgs;
        using implements_type = typename MediaEngineStateChangedEventArgs_base::implements_type;
        using implements_type::implements_type;
        
        hstring GetRuntimeClassName() const override
        {
            return L"CommunityToolkit.Maui.Media.WinRT.MediaEngineStateChangedEventArgs";
        }
    };
}
namespace winrt::CommunityToolkit::Maui::Media::WinRT::factory_implementation
{
    template <typename D, typename T, typename... I>
    struct WINRT_IMPL_EMPTY_BASES MediaEngineStateChangedEventArgsT : implements<D, winrt::Windows::Foundation::IActivationFactory, winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineStateChangedEventArgsFactory, I...>
    {
        using instance_type = CommunityToolkit::Maui::Media::WinRT::MediaEngineStateChangedEventArgs;

        hstring GetRuntimeClassName() const
        {
            return L"CommunityToolkit.Maui.Media.WinRT.MediaEngineStateChangedEventArgs";
        }
        auto CreateInstance(std::int32_t oldState, std::int32_t newState)
        {
            return make<T>(oldState, newState);
        }
        [[noreturn]] winrt::Windows::Foundation::IInspectable ActivateInstance() const
        {
            throw hresult_not_implemented();
        }
    };
}

#if defined(WINRT_FORCE_INCLUDE_MEDIAENGINESTATECHANGEDEVENTARGS_XAML_G_H) || __has_include("MediaEngineStateChangedEventArgs.xaml.g.h")

#include "MediaEngineStateChangedEventArgs.xaml.g.h"

#else

namespace winrt::CommunityToolkit::Maui::Media::WinRT::implementation
{
    template <typename D, typename... I>
    using MediaEngineStateChangedEventArgsT = MediaEngineStateChangedEventArgs_base<D, I...>;
}

#endif
