// WARNING: Please don't edit this file. It was generated by C++/WinRT v3.0.260715.1

#pragma once
#ifdef WINRT_IMPORT_MODULE
#include "winrt/base_macros.h"
import winrt.CommunityToolkit.Maui.Media.WinRT;
#else // WINRT_IMPORT_MODULE
#include "winrt/CommunityToolkit.Maui.Media.WinRT.h"
#endif // WINRT_IMPORT_MODULE
namespace winrt::CommunityToolkit::Maui::Media::WinRT::implementation
{
    template <typename D, typename... I>
    struct WINRT_IMPL_EMPTY_BASES MediaEngineTimeChangedEventArgs_base : implements<D, CommunityToolkit::Maui::Media::WinRT::MediaEngineTimeChangedEventArgs, I...>
    {
        using base_type = MediaEngineTimeChangedEventArgs_base;
        using class_type = CommunityToolkit::Maui::Media::WinRT::MediaEngineTimeChangedEventArgs;
        using implements_type = typename MediaEngineTimeChangedEventArgs_base::implements_type;
        using implements_type::implements_type;
        
        hstring GetRuntimeClassName() const override
        {
            return L"CommunityToolkit.Maui.Media.WinRT.MediaEngineTimeChangedEventArgs";
        }
    };
}
namespace winrt::CommunityToolkit::Maui::Media::WinRT::factory_implementation
{
    template <typename D, typename T, typename... I>
    struct WINRT_IMPL_EMPTY_BASES MediaEngineTimeChangedEventArgsT : implements<D, winrt::Windows::Foundation::IActivationFactory, winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineTimeChangedEventArgsFactory, I...>
    {
        using instance_type = CommunityToolkit::Maui::Media::WinRT::MediaEngineTimeChangedEventArgs;

        hstring GetRuntimeClassName() const
        {
            return L"CommunityToolkit.Maui.Media.WinRT.MediaEngineTimeChangedEventArgs";
        }
        auto CreateInstance(double positionSeconds, double durationSeconds)
        {
            return make<T>(positionSeconds, durationSeconds);
        }
        [[noreturn]] winrt::Windows::Foundation::IInspectable ActivateInstance() const
        {
            throw hresult_not_implemented();
        }
    };
}

#if defined(WINRT_FORCE_INCLUDE_MEDIAENGINETIMECHANGEDEVENTARGS_XAML_G_H) || __has_include("MediaEngineTimeChangedEventArgs.xaml.g.h")

#include "MediaEngineTimeChangedEventArgs.xaml.g.h"

#else

namespace winrt::CommunityToolkit::Maui::Media::WinRT::implementation
{
    template <typename D, typename... I>
    using MediaEngineTimeChangedEventArgsT = MediaEngineTimeChangedEventArgs_base<D, I...>;
}

#endif
