// WARNING: Please don't edit this file. It was generated by C++/WinRT v3.0.260715.1

void* winrt_make_CommunityToolkit_Maui_Media_WinRT_MediaEngineSizeChangedEventArgs()
{
    return winrt::detach_abi(winrt::make<winrt::CommunityToolkit::Maui::Media::WinRT::factory_implementation::MediaEngineSizeChangedEventArgs>());
}
WINRT_EXPORT namespace winrt::CommunityToolkit::Maui::Media::WinRT
{
    MediaEngineSizeChangedEventArgs::MediaEngineSizeChangedEventArgs(std::uint32_t width, std::uint32_t height) :
        MediaEngineSizeChangedEventArgs(make<CommunityToolkit::Maui::Media::WinRT::implementation::MediaEngineSizeChangedEventArgs>(width, height))
    {
    }
}
