// WARNING: Please don't edit this file. It was generated by C++/WinRT v3.0.260715.1

void* winrt_make_CommunityToolkit_Maui_Media_WinRT_MediaEngineErrorEventArgs()
{
    return winrt::detach_abi(winrt::make<winrt::CommunityToolkit::Maui::Media::WinRT::factory_implementation::MediaEngineErrorEventArgs>());
}
WINRT_EXPORT namespace winrt::CommunityToolkit::Maui::Media::WinRT
{
    MediaEngineErrorEventArgs::MediaEngineErrorEventArgs(std::int32_t errorCode, param::hstring const& errorMessage) :
        MediaEngineErrorEventArgs(make<CommunityToolkit::Maui::Media::WinRT::implementation::MediaEngineErrorEventArgs>(errorCode, errorMessage))
    {
    }
}
