// WARNING: Please don't edit this file. It was generated by C++/WinRT v3.0.260715.1

#pragma once
#ifdef WINRT_IMPORT_MODULE
#include "winrt/base_macros.h"
import winrt.CommunityToolkit.Maui.Media.WinRT;
#else // WINRT_IMPORT_MODULE
#include "winrt/CommunityToolkit.Maui.Media.WinRT.h"
#endif // WINRT_IMPORT_MODULE
namespace winrt::CommunityToolkit::Maui::Media::WinRT::implementation
{
    template <typename D, typename... I>
    struct WINRT_IMPL_EMPTY_BASES MediaEngineErrorEventArgs_base : implements<D, CommunityToolkit::Maui::Media::WinRT::MediaEngineErrorEventArgs, I...>
    {
        using base_type = MediaEngineErrorEventArgs_base;
        using class_type = CommunityToolkit::Maui::Media::WinRT::MediaEngineErrorEventArgs;
        using implements_type = typename MediaEngineErrorEventArgs_base::implements_type;
        using implements_type::implements_type;
        
        hstring GetRuntimeClassName() const override
        {
            return L"CommunityToolkit.Maui.Media.WinRT.MediaEngineErrorEventArgs";
        }
    };
}
namespace winrt::CommunityToolkit::Maui::Media::WinRT::factory_implementation
{
    template <typename D, typename T, typename... I>
    struct WINRT_IMPL_EMPTY_BASES MediaEngineErrorEventArgsT : implements<D, winrt::Windows::Foundation::IActivationFactory, winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineErrorEventArgsFactory, I...>
    {
        using instance_type = CommunityToolkit::Maui::Media::WinRT::MediaEngineErrorEventArgs;

        hstring GetRuntimeClassName() const
        {
            return L"CommunityToolkit.Maui.Media.WinRT.MediaEngineErrorEventArgs";
        }
        auto CreateInstance(std::int32_t errorCode, hstring const& errorMessage)
        {
            return make<T>(errorCode, errorMessage);
        }
        [[noreturn]] winrt::Windows::Foundation::IInspectable ActivateInstance() const
        {
            throw hresult_not_implemented();
        }
    };
}

#if defined(WINRT_FORCE_INCLUDE_MEDIAENGINEERROREVENTARGS_XAML_G_H) || __has_include("MediaEngineErrorEventArgs.xaml.g.h")

#include "MediaEngineErrorEventArgs.xaml.g.h"

#else

namespace winrt::CommunityToolkit::Maui::Media::WinRT::implementation
{
    template <typename D, typename... I>
    using MediaEngineErrorEventArgsT = MediaEngineErrorEventArgs_base<D, I...>;
}

#endif
