// WARNING: Please don't edit this file. It was generated by C++/WinRT v3.0.260715.1

#include "pch.h"
#include "winrt/base.h"
void* winrt_make_CommunityToolkit_Maui_Media_WinRT_DrmLicenseAcquiredEventArgs();
void* winrt_make_CommunityToolkit_Maui_Media_WinRT_MediaEngineErrorEventArgs();
void* winrt_make_CommunityToolkit_Maui_Media_WinRT_MediaEngineSizeChangedEventArgs();
void* winrt_make_CommunityToolkit_Maui_Media_WinRT_MediaEngineStateChangedEventArgs();
void* winrt_make_CommunityToolkit_Maui_Media_WinRT_MediaEngineTimeChangedEventArgs();
void* winrt_make_CommunityToolkit_Maui_Media_WinRT_PlayReadyDrmConfiguration();
void* winrt_make_CommunityToolkit_Maui_Media_WinRT_PlayReadyMediaEngine();

bool __stdcall winrt_can_unload_now() noexcept
{
    if (winrt::get_module_lock())
    {
        return false;
    }

    winrt::clear_factory_cache();
    return true;
}

void* __stdcall winrt_get_activation_factory([[maybe_unused]] std::wstring_view const& name)
{
    auto requal = [](std::wstring_view const& left, std::wstring_view const& right) noexcept
    {
        return std::equal(left.rbegin(), left.rend(), right.rbegin(), right.rend());
    };

    if (requal(name, L"CommunityToolkit.Maui.Media.WinRT.DrmLicenseAcquiredEventArgs"))
    {
        return winrt_make_CommunityToolkit_Maui_Media_WinRT_DrmLicenseAcquiredEventArgs();
    }

    if (requal(name, L"CommunityToolkit.Maui.Media.WinRT.MediaEngineErrorEventArgs"))
    {
        return winrt_make_CommunityToolkit_Maui_Media_WinRT_MediaEngineErrorEventArgs();
    }

    if (requal(name, L"CommunityToolkit.Maui.Media.WinRT.MediaEngineSizeChangedEventArgs"))
    {
        return winrt_make_CommunityToolkit_Maui_Media_WinRT_MediaEngineSizeChangedEventArgs();
    }

    if (requal(name, L"CommunityToolkit.Maui.Media.WinRT.MediaEngineStateChangedEventArgs"))
    {
        return winrt_make_CommunityToolkit_Maui_Media_WinRT_MediaEngineStateChangedEventArgs();
    }

    if (requal(name, L"CommunityToolkit.Maui.Media.WinRT.MediaEngineTimeChangedEventArgs"))
    {
        return winrt_make_CommunityToolkit_Maui_Media_WinRT_MediaEngineTimeChangedEventArgs();
    }

    if (requal(name, L"CommunityToolkit.Maui.Media.WinRT.PlayReadyDrmConfiguration"))
    {
        return winrt_make_CommunityToolkit_Maui_Media_WinRT_PlayReadyDrmConfiguration();
    }

    if (requal(name, L"CommunityToolkit.Maui.Media.WinRT.PlayReadyMediaEngine"))
    {
        return winrt_make_CommunityToolkit_Maui_Media_WinRT_PlayReadyMediaEngine();
    }

    return nullptr;
}

std::int32_t __stdcall WINRT_CanUnloadNow() noexcept
{
#ifdef _WRL_MODULE_H_
#ifdef _MSC_VER
#pragma warning(suppress: 4324) // structure was padded due to alignment specifier
#endif
    if (!::Microsoft::WRL::Module<::Microsoft::WRL::InProc>::GetModule().Terminate())
    {
        return 1;
    }
#endif

    return winrt_can_unload_now() ? 0 : 1;
}

std::int32_t __stdcall WINRT_GetActivationFactory(void* classId, void** factory) noexcept try
{
    std::wstring_view const name{ *reinterpret_cast<winrt::hstring*>(&classId) };
    *factory = winrt_get_activation_factory(name);

    if (*factory)
    {
        return 0;
    }

#ifdef _WRL_MODULE_H_
#pragma warning(suppress: 4324) // structure was padded due to alignment specifier
    return ::Microsoft::WRL::Module<::Microsoft::WRL::InProc>::GetModule().GetActivationFactory(static_cast<HSTRING>(classId), reinterpret_cast<::IActivationFactory**>(factory));
#else
    return winrt::hresult_class_not_available(name).to_abi();
#endif
}
catch (...) { return winrt::to_hresult(); }
