// WARNING: Please don't edit this file. It was generated by C++/WinRT v3.0.260715.1

void* winrt_make_CommunityToolkit_Maui_Media_WinRT_PlayReadyMediaEngine()
{
    return winrt::detach_abi(winrt::make<winrt::CommunityToolkit::Maui::Media::WinRT::factory_implementation::PlayReadyMediaEngine>());
}
WINRT_EXPORT namespace winrt::CommunityToolkit::Maui::Media::WinRT
{
    PlayReadyMediaEngine::PlayReadyMediaEngine() :
        PlayReadyMediaEngine(make<CommunityToolkit::Maui::Media::WinRT::implementation::PlayReadyMediaEngine>())
    {
    }
}
