// WARNING: Please don't edit this file. It was generated by C++/WinRT v3.0.260715.1

#pragma once
#ifdef WINRT_IMPORT_MODULE
#include "winrt/base_macros.h"
import winrt.CommunityToolkit.Maui.Media.WinRT;
#else // WINRT_IMPORT_MODULE
#include "winrt/CommunityToolkit.Maui.Media.WinRT.h"
#endif // WINRT_IMPORT_MODULE
namespace winrt::CommunityToolkit::Maui::Media::WinRT::implementation
{
    template <typename D, typename... I>
    struct WINRT_IMPL_EMPTY_BASES PlayReadyMediaEngine_base : implements<D, CommunityToolkit::Maui::Media::WinRT::PlayReadyMediaEngine, I...>
    {
        using base_type = PlayReadyMediaEngine_base;
        using class_type = CommunityToolkit::Maui::Media::WinRT::PlayReadyMediaEngine;
        using implements_type = typename PlayReadyMediaEngine_base::implements_type;
        using implements_type::implements_type;
        
        hstring GetRuntimeClassName() const override
        {
            return L"CommunityToolkit.Maui.Media.WinRT.PlayReadyMediaEngine";
        }
    };
}
namespace winrt::CommunityToolkit::Maui::Media::WinRT::factory_implementation
{
    template <typename D, typename T, typename... I>
    struct WINRT_IMPL_EMPTY_BASES PlayReadyMediaEngineT : implements<D, winrt::Windows::Foundation::IActivationFactory, I...>
    {
        using instance_type = CommunityToolkit::Maui::Media::WinRT::PlayReadyMediaEngine;

        hstring GetRuntimeClassName() const
        {
            return L"CommunityToolkit.Maui.Media.WinRT.PlayReadyMediaEngine";
        }
        auto ActivateInstance() const
        {
            return make<T>();
        }
    };
}

#if defined(WINRT_FORCE_INCLUDE_PLAYREADYMEDIAENGINE_XAML_G_H) || __has_include("PlayReadyMediaEngine.xaml.g.h")

#include "PlayReadyMediaEngine.xaml.g.h"

#else

namespace winrt::CommunityToolkit::Maui::Media::WinRT::implementation
{
    template <typename D, typename... I>
    using PlayReadyMediaEngineT = PlayReadyMediaEngine_base<D, I...>;
}

#endif
