// WARNING: Please don't edit this file. It was generated by C++/WinRT v3.0.260715.1

void* winrt_make_CommunityToolkit_Maui_Media_WinRT_PlayReadyDrmConfiguration()
{
    return winrt::detach_abi(winrt::make<winrt::CommunityToolkit::Maui::Media::WinRT::factory_implementation::PlayReadyDrmConfiguration>());
}
WINRT_EXPORT namespace winrt::CommunityToolkit::Maui::Media::WinRT
{
    PlayReadyDrmConfiguration::PlayReadyDrmConfiguration() :
        PlayReadyDrmConfiguration(make<CommunityToolkit::Maui::Media::WinRT::implementation::PlayReadyDrmConfiguration>())
    {
    }
}
