#pragma once

#include "pch.h"

// Generated C++/WinRT headers for the runtime classes declared in PlayReadyMediaEngine.idl
#include "Generated Files/PlayReadyDrmConfiguration.g.h"
#include "Generated Files/MediaEngineErrorEventArgs.g.h"
#include "Generated Files/MediaEngineTimeChangedEventArgs.g.h"
#include "Generated Files/MediaEngineStateChangedEventArgs.g.h"
#include "Generated Files/MediaEngineSizeChangedEventArgs.g.h"
#include "Generated Files/DrmLicenseAcquiredEventArgs.g.h"

namespace winrt::CommunityToolkit::Maui::Media::WinRT::implementation
{
	// C++/WinRT v3.0's _base template (and underlying implements<> / root_implements<>)
	// only provides default construction. For runtime classes with parameterized
	// constructors, we store the constructor arguments as member fields and expose
	// property getters. The produce<> code generated by cppwinrt.exe calls
	// shim().PropertyName() to read property values at the ABI boundary.

	/// <summary>
	/// PlayReady DRM configuration data (license server URL + custom HTTP headers).
	/// </summary>
	struct PlayReadyDrmConfiguration : PlayReadyDrmConfigurationT<PlayReadyDrmConfiguration>
	{
		PlayReadyDrmConfiguration() = default;

		// Property storage & accessors
		hstring LicenseServerUrl() const { return m_licenseServerUrl; }
		void LicenseServerUrl(hstring const& value) { m_licenseServerUrl = value; }
		Windows::Foundation::Collections::IMap<hstring, hstring> CustomHeaders() const { return m_customHeaders; }
		void CustomHeaders(Windows::Foundation::Collections::IMap<hstring, hstring> const& value) { m_customHeaders = value; }

	private:
		hstring m_licenseServerUrl;
		Windows::Foundation::Collections::IMap<hstring, hstring> m_customHeaders{ nullptr };
	};

	/// <summary>
	/// Event args for media engine errors.
	/// </summary>
	struct MediaEngineErrorEventArgs : MediaEngineErrorEventArgsT<MediaEngineErrorEventArgs>
	{
		MediaEngineErrorEventArgs(int32_t errorCode, hstring const& errorMessage)
			: m_errorCode(errorCode), m_errorMessage(errorMessage)
		{
		}

		int32_t ErrorCode() const { return m_errorCode; }
		hstring ErrorMessage() const { return m_errorMessage; }

	private:
		int32_t m_errorCode = 0;
		hstring m_errorMessage;
	};

	/// <summary>
	/// Event args for time position/duration updates.
	/// </summary>
	struct MediaEngineTimeChangedEventArgs : MediaEngineTimeChangedEventArgsT<MediaEngineTimeChangedEventArgs>
	{
		MediaEngineTimeChangedEventArgs(double positionSeconds, double durationSeconds)
			: m_positionSeconds(positionSeconds), m_durationSeconds(durationSeconds)
		{
		}

		double PositionSeconds() const { return m_positionSeconds; }
		double DurationSeconds() const { return m_durationSeconds; }

	private:
		double m_positionSeconds = 0.0;
		double m_durationSeconds = 0.0;
	};

	/// <summary>
	/// Event args for playback state transitions.
	/// </summary>
	struct MediaEngineStateChangedEventArgs : MediaEngineStateChangedEventArgsT<MediaEngineStateChangedEventArgs>
	{
		MediaEngineStateChangedEventArgs(int32_t oldState, int32_t newState)
			: m_oldState(oldState), m_newState(newState)
		{
		}

		int32_t OldState() const { return m_oldState; }
		int32_t NewState() const { return m_newState; }

	private:
		int32_t m_oldState = 0;
		int32_t m_newState = 0;
	};

	/// <summary>
	/// Event args for video dimension changes.
	/// </summary>
	struct MediaEngineSizeChangedEventArgs : MediaEngineSizeChangedEventArgsT<MediaEngineSizeChangedEventArgs>
	{
		MediaEngineSizeChangedEventArgs(uint32_t width, uint32_t height)
			: m_width(width), m_height(height)
		{
		}

		uint32_t Width() const { return m_width; }
		uint32_t Height() const { return m_height; }

	private:
		uint32_t m_width = 0;
		uint32_t m_height = 0;
	};

	/// <summary>
	/// Event args for DRM license acquisition results.
	/// </summary>
	struct DrmLicenseAcquiredEventArgs : DrmLicenseAcquiredEventArgsT<DrmLicenseAcquiredEventArgs>
	{
		DrmLicenseAcquiredEventArgs(bool success, hstring const& errorMessage)
			: m_success(success), m_errorMessage(errorMessage)
		{
		}

		bool Success() const { return m_success; }
		hstring ErrorMessage() const { return m_errorMessage; }

	private:
		bool m_success = false;
		hstring m_errorMessage;
	};
}

namespace winrt::CommunityToolkit::Maui::Media::WinRT::factory_implementation
{
	// Factory implementations for runtime classes.

	struct PlayReadyDrmConfiguration : PlayReadyDrmConfigurationT<PlayReadyDrmConfiguration, implementation::PlayReadyDrmConfiguration>
	{
	};

	struct MediaEngineErrorEventArgs : MediaEngineErrorEventArgsT<MediaEngineErrorEventArgs, implementation::MediaEngineErrorEventArgs>
	{
	};

	struct MediaEngineTimeChangedEventArgs : MediaEngineTimeChangedEventArgsT<MediaEngineTimeChangedEventArgs, implementation::MediaEngineTimeChangedEventArgs>
	{
	};

	struct MediaEngineStateChangedEventArgs : MediaEngineStateChangedEventArgsT<MediaEngineStateChangedEventArgs, implementation::MediaEngineStateChangedEventArgs>
	{
	};

	struct MediaEngineSizeChangedEventArgs : MediaEngineSizeChangedEventArgsT<MediaEngineSizeChangedEventArgs, implementation::MediaEngineSizeChangedEventArgs>
	{
	};

	struct DrmLicenseAcquiredEventArgs : DrmLicenseAcquiredEventArgsT<DrmLicenseAcquiredEventArgs, implementation::DrmLicenseAcquiredEventArgs>
	{
	};
}
