#include "pch.h"
#include "PlayReadyMediaEngine.h"
#include "PlayReadyMediaEngine.g.cpp"

// WARNING: This file is automatically generated by a tool. Do not directly
// add this file to your project, as any changes you make will be lost.
// This file is a stub you can use as a starting point for your implementation.
//
// To add a copy of this file to your project:
//   1. Copy this file from its original location to the location where you store 
//      your other source files (e.g. the project root). 
//   2. Add the copied file to your project. In Visual Studio, you can use 
//      Project -> Add Existing Item.
//   3. Delete this comment and the 'static_assert' (below) from the copied file.
//      Do not modify the original file.
//
// To update an existing file in your project:
//   1. Copy the relevant changes from this file and merge them into the copy 
//      you made previously.
//    
// This assertion helps prevent accidental modification of generated files.
static_assert(false, "This file is generated by a tool and will be overwritten. Open this error and view the comment for assistance.");

namespace winrt::CommunityToolkit::Maui::Media::WinRT::implementation
{
    void PlayReadyMediaEngine::Initialize(std::int64_t swapChainPanelHandle)
    {
        throw hresult_not_implemented();
    }
    void PlayReadyMediaEngine::SetSource(hstring const& url, winrt::CommunityToolkit::Maui::Media::WinRT::PlayReadyDrmConfiguration const& drmConfig)
    {
        throw hresult_not_implemented();
    }
    void PlayReadyMediaEngine::SetSourceFromManifestBytes(winrt::Windows::Foundation::Collections::IVectorView<std::uint8_t> const& manifestData, hstring const& originalUrl, winrt::CommunityToolkit::Maui::Media::WinRT::PlayReadyDrmConfiguration const& drmConfig)
    {
        throw hresult_not_implemented();
    }
    hstring PlayReadyMediaEngine::TestCdmGenerateRequest(hstring const& mp4Path, hstring const& licenseUrl, hstring const& licenseHeaderName, hstring const& licenseHeaderValue)
    {
        throw hresult_not_implemented();
    }
    void PlayReadyMediaEngine::Play()
    {
        throw hresult_not_implemented();
    }
    void PlayReadyMediaEngine::Pause()
    {
        throw hresult_not_implemented();
    }
    void PlayReadyMediaEngine::Seek(double positionSeconds)
    {
        throw hresult_not_implemented();
    }
    void PlayReadyMediaEngine::SetVolume(double volume)
    {
        throw hresult_not_implemented();
    }
    void PlayReadyMediaEngine::SetMuted(bool muted)
    {
        throw hresult_not_implemented();
    }
    void PlayReadyMediaEngine::SetPlaybackRate(double rate)
    {
        throw hresult_not_implemented();
    }
    void PlayReadyMediaEngine::SetLooping(bool looping)
    {
        throw hresult_not_implemented();
    }
    void PlayReadyMediaEngine::SetStretch(std::int32_t stretchMode)
    {
        throw hresult_not_implemented();
    }
    void PlayReadyMediaEngine::ResizeSwapChain(std::uint32_t width, std::uint32_t height)
    {
        throw hresult_not_implemented();
    }
    void PlayReadyMediaEngine::Close()
    {
        throw hresult_not_implemented();
    }
    double PlayReadyMediaEngine::CurrentPositionSeconds()
    {
        throw hresult_not_implemented();
    }
    double PlayReadyMediaEngine::DurationSeconds()
    {
        throw hresult_not_implemented();
    }
    std::uint32_t PlayReadyMediaEngine::NaturalVideoWidth()
    {
        throw hresult_not_implemented();
    }
    std::uint32_t PlayReadyMediaEngine::NaturalVideoHeight()
    {
        throw hresult_not_implemented();
    }
    bool PlayReadyMediaEngine::IsBuffering()
    {
        throw hresult_not_implemented();
    }
    winrt::event_token PlayReadyMediaEngine::MediaOpened(winrt::Windows::Foundation::TypedEventHandler<winrt::CommunityToolkit::Maui::Media::WinRT::PlayReadyMediaEngine, winrt::Windows::Foundation::IInspectable> const& handler)
    {
        throw hresult_not_implemented();
    }
    void PlayReadyMediaEngine::MediaOpened(winrt::event_token const& token) noexcept
    {
        throw hresult_not_implemented();
    }
    winrt::event_token PlayReadyMediaEngine::MediaFailed(winrt::Windows::Foundation::TypedEventHandler<winrt::CommunityToolkit::Maui::Media::WinRT::PlayReadyMediaEngine, winrt::CommunityToolkit::Maui::Media::WinRT::MediaEngineErrorEventArgs> const& handler)
    {
        throw hresult_not_implemented();
    }
    void PlayReadyMediaEngine::MediaFailed(winrt::event_token const& token) noexcept
    {
        throw hresult_not_implemented();
    }
    winrt::event_token PlayReadyMediaEngine::MediaEnded(winrt::Windows::Foundation::TypedEventHandler<winrt::CommunityToolkit::Maui::Media::WinRT::PlayReadyMediaEngine, winrt::Windows::Foundation::IInspectable> const& handler)
    {
        throw hresult_not_implemented();
    }
    void PlayReadyMediaEngine::MediaEnded(winrt::event_token const& token) noexcept
    {
        throw hresult_not_implemented();
    }
    winrt::event_token PlayReadyMediaEngine::TimeChanged(winrt::Windows::Foundation::TypedEventHandler<winrt::CommunityToolkit::Maui::Media::WinRT::PlayReadyMediaEngine, winrt::CommunityToolkit::Maui::Media::WinRT::MediaEngineTimeChangedEventArgs> const& handler)
    {
        throw hresult_not_implemented();
    }
    void PlayReadyMediaEngine::TimeChanged(winrt::event_token const& token) noexcept
    {
        throw hresult_not_implemented();
    }
    winrt::event_token PlayReadyMediaEngine::BufferingChanged(winrt::Windows::Foundation::TypedEventHandler<winrt::CommunityToolkit::Maui::Media::WinRT::PlayReadyMediaEngine, bool> const& handler)
    {
        throw hresult_not_implemented();
    }
    void PlayReadyMediaEngine::BufferingChanged(winrt::event_token const& token) noexcept
    {
        throw hresult_not_implemented();
    }
    winrt::event_token PlayReadyMediaEngine::SizeChanged(winrt::Windows::Foundation::TypedEventHandler<winrt::CommunityToolkit::Maui::Media::WinRT::PlayReadyMediaEngine, winrt::CommunityToolkit::Maui::Media::WinRT::MediaEngineSizeChangedEventArgs> const& handler)
    {
        throw hresult_not_implemented();
    }
    void PlayReadyMediaEngine::SizeChanged(winrt::event_token const& token) noexcept
    {
        throw hresult_not_implemented();
    }
    winrt::event_token PlayReadyMediaEngine::LicenseAcquired(winrt::Windows::Foundation::TypedEventHandler<winrt::CommunityToolkit::Maui::Media::WinRT::PlayReadyMediaEngine, winrt::CommunityToolkit::Maui::Media::WinRT::DrmLicenseAcquiredEventArgs> const& handler)
    {
        throw hresult_not_implemented();
    }
    void PlayReadyMediaEngine::LicenseAcquired(winrt::event_token const& token) noexcept
    {
        throw hresult_not_implemented();
    }
    winrt::event_token PlayReadyMediaEngine::StateChanged(winrt::Windows::Foundation::TypedEventHandler<winrt::CommunityToolkit::Maui::Media::WinRT::PlayReadyMediaEngine, winrt::CommunityToolkit::Maui::Media::WinRT::MediaEngineStateChangedEventArgs> const& handler)
    {
        throw hresult_not_implemented();
    }
    void PlayReadyMediaEngine::StateChanged(winrt::event_token const& token) noexcept
    {
        throw hresult_not_implemented();
    }
}
