#pragma once
#include "PlayReadyMediaEngine.g.h"

// WARNING: This file is automatically generated by a tool. Do not directly
// add this file to your project, as any changes you make will be lost.
// This file is a stub you can use as a starting point for your implementation.
//
// To add a copy of this file to your project:
//   1. Copy this file from its original location to the location where you store 
//      your other source files (e.g. the project root). 
//   2. Add the copied file to your project. In Visual Studio, you can use 
//      Project -> Add Existing Item.
//   3. Delete this comment and the 'static_assert' (below) from the copied file.
//      Do not modify the original file.
//
// To update an existing file in your project:
//   1. Copy the relevant changes from this file and merge them into the copy 
//      you made previously.
//    
// This assertion helps prevent accidental modification of generated files.
static_assert(false, "This file is generated by a tool and will be overwritten. Open this error and view the comment for assistance.");

namespace winrt::CommunityToolkit::Maui::Media::WinRT::implementation
{
    struct PlayReadyMediaEngine : PlayReadyMediaEngineT<PlayReadyMediaEngine>
    {
        PlayReadyMediaEngine() = default;

        void Initialize(std::int64_t swapChainPanelHandle);
        void SetSource(hstring const& url, winrt::CommunityToolkit::Maui::Media::WinRT::PlayReadyDrmConfiguration const& drmConfig);
        void SetSourceFromManifestBytes(winrt::Windows::Foundation::Collections::IVectorView<std::uint8_t> const& manifestData, hstring const& originalUrl, winrt::CommunityToolkit::Maui::Media::WinRT::PlayReadyDrmConfiguration const& drmConfig);
        hstring TestCdmGenerateRequest(hstring const& mp4Path, hstring const& licenseUrl, hstring const& licenseHeaderName, hstring const& licenseHeaderValue);
        void Play();
        void Pause();
        void Seek(double positionSeconds);
        void SetVolume(double volume);
        void SetMuted(bool muted);
        void SetPlaybackRate(double rate);
        void SetLooping(bool looping);
        void SetStretch(std::int32_t stretchMode);
        void ResizeSwapChain(std::uint32_t width, std::uint32_t height);
        void Close();
        double CurrentPositionSeconds();
        double DurationSeconds();
        std::uint32_t NaturalVideoWidth();
        std::uint32_t NaturalVideoHeight();
        bool IsBuffering();
        winrt::event_token MediaOpened(winrt::Windows::Foundation::TypedEventHandler<winrt::CommunityToolkit::Maui::Media::WinRT::PlayReadyMediaEngine, winrt::Windows::Foundation::IInspectable> const& handler);
        void MediaOpened(winrt::event_token const& token) noexcept;
        winrt::event_token MediaFailed(winrt::Windows::Foundation::TypedEventHandler<winrt::CommunityToolkit::Maui::Media::WinRT::PlayReadyMediaEngine, winrt::CommunityToolkit::Maui::Media::WinRT::MediaEngineErrorEventArgs> const& handler);
        void MediaFailed(winrt::event_token const& token) noexcept;
        winrt::event_token MediaEnded(winrt::Windows::Foundation::TypedEventHandler<winrt::CommunityToolkit::Maui::Media::WinRT::PlayReadyMediaEngine, winrt::Windows::Foundation::IInspectable> const& handler);
        void MediaEnded(winrt::event_token const& token) noexcept;
        winrt::event_token TimeChanged(winrt::Windows::Foundation::TypedEventHandler<winrt::CommunityToolkit::Maui::Media::WinRT::PlayReadyMediaEngine, winrt::CommunityToolkit::Maui::Media::WinRT::MediaEngineTimeChangedEventArgs> const& handler);
        void TimeChanged(winrt::event_token const& token) noexcept;
        winrt::event_token BufferingChanged(winrt::Windows::Foundation::TypedEventHandler<winrt::CommunityToolkit::Maui::Media::WinRT::PlayReadyMediaEngine, bool> const& handler);
        void BufferingChanged(winrt::event_token const& token) noexcept;
        winrt::event_token SizeChanged(winrt::Windows::Foundation::TypedEventHandler<winrt::CommunityToolkit::Maui::Media::WinRT::PlayReadyMediaEngine, winrt::CommunityToolkit::Maui::Media::WinRT::MediaEngineSizeChangedEventArgs> const& handler);
        void SizeChanged(winrt::event_token const& token) noexcept;
        winrt::event_token LicenseAcquired(winrt::Windows::Foundation::TypedEventHandler<winrt::CommunityToolkit::Maui::Media::WinRT::PlayReadyMediaEngine, winrt::CommunityToolkit::Maui::Media::WinRT::DrmLicenseAcquiredEventArgs> const& handler);
        void LicenseAcquired(winrt::event_token const& token) noexcept;
        winrt::event_token StateChanged(winrt::Windows::Foundation::TypedEventHandler<winrt::CommunityToolkit::Maui::Media::WinRT::PlayReadyMediaEngine, winrt::CommunityToolkit::Maui::Media::WinRT::MediaEngineStateChangedEventArgs> const& handler);
        void StateChanged(winrt::event_token const& token) noexcept;
    };
}
namespace winrt::CommunityToolkit::Maui::Media::WinRT::factory_implementation
{
    struct PlayReadyMediaEngine : PlayReadyMediaEngineT<PlayReadyMediaEngine, implementation::PlayReadyMediaEngine>
    {
    };
}
