// WARNING: Please don't edit this file. It was generated by C++/WinRT v3.0.260715.1

#pragma once
#ifndef WINRT_CommunityToolkit_Maui_Media_WinRT_H
#define WINRT_CommunityToolkit_Maui_Media_WinRT_H
#ifndef WINRT_IMPORT_MODULE

#ifndef WINRT_IMPL_BUILD_MODULE
#include "winrt/base.h"
static_assert(winrt::check_version(CPPWINRT_VERSION, "3.0.260715.1"), "Mismatched C++/WinRT headers.");
#define CPPWINRT_VERSION "3.0.260715.1"
#include "winrt/impl/Windows.Foundation.2.h"
#include "winrt/impl/Windows.Foundation.Collections.2.h"
#include "winrt/impl/CommunityToolkit.Maui.Media.WinRT.2.h"
#endif // WINRT_IMPL_BUILD_MODULE
WINRT_EXPORT namespace winrt::impl
{
    template <typename D> auto consume_CommunityToolkit_Maui_Media_WinRT_IDrmLicenseAcquiredEventArgs<D>::Success() const
    {
        bool value{};
        consume_general<winrt::CommunityToolkit::Maui::Media::WinRT::IDrmLicenseAcquiredEventArgs, D>(static_cast<D const*>(this), &abi_t<winrt::CommunityToolkit::Maui::Media::WinRT::IDrmLicenseAcquiredEventArgs>::get_Success, &value);
        return value;
    }
    template <typename D> auto consume_CommunityToolkit_Maui_Media_WinRT_IDrmLicenseAcquiredEventArgs<D>::ErrorMessage() const
    {
        void* value{};
        consume_general<winrt::CommunityToolkit::Maui::Media::WinRT::IDrmLicenseAcquiredEventArgs, D>(static_cast<D const*>(this), &abi_t<winrt::CommunityToolkit::Maui::Media::WinRT::IDrmLicenseAcquiredEventArgs>::get_ErrorMessage, &value);
        return hstring{ value, take_ownership_from_abi };
    }
    template <typename D> auto consume_CommunityToolkit_Maui_Media_WinRT_IDrmLicenseAcquiredEventArgsFactory<D>::CreateInstance(bool success, param::hstring const& errorMessage) const
    {
        void* value{};
        consume_general<winrt::CommunityToolkit::Maui::Media::WinRT::IDrmLicenseAcquiredEventArgsFactory, D>(static_cast<D const*>(this), &abi_t<winrt::CommunityToolkit::Maui::Media::WinRT::IDrmLicenseAcquiredEventArgsFactory>::CreateInstance, success, *(void**)(&errorMessage), &value);
        return winrt::CommunityToolkit::Maui::Media::WinRT::DrmLicenseAcquiredEventArgs{ value, take_ownership_from_abi };
    }
    template <typename D> auto consume_CommunityToolkit_Maui_Media_WinRT_IMediaEngineErrorEventArgs<D>::ErrorCode() const
    {
        std::int32_t value{};
        consume_general<winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineErrorEventArgs, D>(static_cast<D const*>(this), &abi_t<winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineErrorEventArgs>::get_ErrorCode, &value);
        return value;
    }
    template <typename D> auto consume_CommunityToolkit_Maui_Media_WinRT_IMediaEngineErrorEventArgs<D>::ErrorMessage() const
    {
        void* value{};
        consume_general<winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineErrorEventArgs, D>(static_cast<D const*>(this), &abi_t<winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineErrorEventArgs>::get_ErrorMessage, &value);
        return hstring{ value, take_ownership_from_abi };
    }
    template <typename D> auto consume_CommunityToolkit_Maui_Media_WinRT_IMediaEngineErrorEventArgsFactory<D>::CreateInstance(std::int32_t errorCode, param::hstring const& errorMessage) const
    {
        void* value{};
        consume_general<winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineErrorEventArgsFactory, D>(static_cast<D const*>(this), &abi_t<winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineErrorEventArgsFactory>::CreateInstance, errorCode, *(void**)(&errorMessage), &value);
        return winrt::CommunityToolkit::Maui::Media::WinRT::MediaEngineErrorEventArgs{ value, take_ownership_from_abi };
    }
    template <typename D> auto consume_CommunityToolkit_Maui_Media_WinRT_IMediaEngineSizeChangedEventArgs<D>::Width() const
    {
        std::uint32_t value{};
        consume_general<winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineSizeChangedEventArgs, D>(static_cast<D const*>(this), &abi_t<winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineSizeChangedEventArgs>::get_Width, &value);
        return value;
    }
    template <typename D> auto consume_CommunityToolkit_Maui_Media_WinRT_IMediaEngineSizeChangedEventArgs<D>::Height() const
    {
        std::uint32_t value{};
        consume_general<winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineSizeChangedEventArgs, D>(static_cast<D const*>(this), &abi_t<winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineSizeChangedEventArgs>::get_Height, &value);
        return value;
    }
    template <typename D> auto consume_CommunityToolkit_Maui_Media_WinRT_IMediaEngineSizeChangedEventArgsFactory<D>::CreateInstance(std::uint32_t width, std::uint32_t height) const
    {
        void* value{};
        consume_general<winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineSizeChangedEventArgsFactory, D>(static_cast<D const*>(this), &abi_t<winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineSizeChangedEventArgsFactory>::CreateInstance, width, height, &value);
        return winrt::CommunityToolkit::Maui::Media::WinRT::MediaEngineSizeChangedEventArgs{ value, take_ownership_from_abi };
    }
    template <typename D> auto consume_CommunityToolkit_Maui_Media_WinRT_IMediaEngineStateChangedEventArgs<D>::OldState() const
    {
        std::int32_t value{};
        consume_general<winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineStateChangedEventArgs, D>(static_cast<D const*>(this), &abi_t<winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineStateChangedEventArgs>::get_OldState, &value);
        return value;
    }
    template <typename D> auto consume_CommunityToolkit_Maui_Media_WinRT_IMediaEngineStateChangedEventArgs<D>::NewState() const
    {
        std::int32_t value{};
        consume_general<winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineStateChangedEventArgs, D>(static_cast<D const*>(this), &abi_t<winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineStateChangedEventArgs>::get_NewState, &value);
        return value;
    }
    template <typename D> auto consume_CommunityToolkit_Maui_Media_WinRT_IMediaEngineStateChangedEventArgsFactory<D>::CreateInstance(std::int32_t oldState, std::int32_t newState) const
    {
        void* value{};
        consume_general<winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineStateChangedEventArgsFactory, D>(static_cast<D const*>(this), &abi_t<winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineStateChangedEventArgsFactory>::CreateInstance, oldState, newState, &value);
        return winrt::CommunityToolkit::Maui::Media::WinRT::MediaEngineStateChangedEventArgs{ value, take_ownership_from_abi };
    }
    template <typename D> auto consume_CommunityToolkit_Maui_Media_WinRT_IMediaEngineTimeChangedEventArgs<D>::PositionSeconds() const
    {
        double value{};
        consume_general<winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineTimeChangedEventArgs, D>(static_cast<D const*>(this), &abi_t<winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineTimeChangedEventArgs>::get_PositionSeconds, &value);
        return value;
    }
    template <typename D> auto consume_CommunityToolkit_Maui_Media_WinRT_IMediaEngineTimeChangedEventArgs<D>::DurationSeconds() const
    {
        double value{};
        consume_general<winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineTimeChangedEventArgs, D>(static_cast<D const*>(this), &abi_t<winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineTimeChangedEventArgs>::get_DurationSeconds, &value);
        return value;
    }
    template <typename D> auto consume_CommunityToolkit_Maui_Media_WinRT_IMediaEngineTimeChangedEventArgsFactory<D>::CreateInstance(double positionSeconds, double durationSeconds) const
    {
        void* value{};
        consume_general<winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineTimeChangedEventArgsFactory, D>(static_cast<D const*>(this), &abi_t<winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineTimeChangedEventArgsFactory>::CreateInstance, positionSeconds, durationSeconds, &value);
        return winrt::CommunityToolkit::Maui::Media::WinRT::MediaEngineTimeChangedEventArgs{ value, take_ownership_from_abi };
    }
    template <typename D> auto consume_CommunityToolkit_Maui_Media_WinRT_IPlayReadyDrmConfiguration<D>::LicenseServerUrl() const
    {
        void* value{};
        consume_general<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyDrmConfiguration, D>(static_cast<D const*>(this), &abi_t<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyDrmConfiguration>::get_LicenseServerUrl, &value);
        return hstring{ value, take_ownership_from_abi };
    }
    template <typename D> auto consume_CommunityToolkit_Maui_Media_WinRT_IPlayReadyDrmConfiguration<D>::LicenseServerUrl(param::hstring const& value) const
    {
        consume_general<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyDrmConfiguration, D>(static_cast<D const*>(this), &abi_t<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyDrmConfiguration>::put_LicenseServerUrl, *(void**)(&value));
    }
    template <typename D> auto consume_CommunityToolkit_Maui_Media_WinRT_IPlayReadyDrmConfiguration<D>::CustomHeaders() const
    {
        void* value{};
        consume_general<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyDrmConfiguration, D>(static_cast<D const*>(this), &abi_t<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyDrmConfiguration>::get_CustomHeaders, &value);
        return winrt::Windows::Foundation::Collections::IMap<hstring, hstring>{ value, take_ownership_from_abi };
    }
    template <typename D> auto consume_CommunityToolkit_Maui_Media_WinRT_IPlayReadyDrmConfiguration<D>::CustomHeaders(param::map<hstring, hstring> const& value) const
    {
        consume_general<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyDrmConfiguration, D>(static_cast<D const*>(this), &abi_t<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyDrmConfiguration>::put_CustomHeaders, *(void**)(&value));
    }
    template <typename D> auto consume_CommunityToolkit_Maui_Media_WinRT_IPlayReadyMediaEngine<D>::Initialize(std::int64_t swapChainPanelHandle) const
    {
        consume_general<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyMediaEngine, D>(static_cast<D const*>(this), &abi_t<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyMediaEngine>::Initialize, swapChainPanelHandle);
    }
    template <typename D> auto consume_CommunityToolkit_Maui_Media_WinRT_IPlayReadyMediaEngine<D>::SetSource(param::hstring const& url, winrt::CommunityToolkit::Maui::Media::WinRT::PlayReadyDrmConfiguration const& drmConfig) const
    {
        consume_general<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyMediaEngine, D>(static_cast<D const*>(this), &abi_t<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyMediaEngine>::SetSource, *(void**)(&url), *(void**)(&drmConfig));
    }
    template <typename D> auto consume_CommunityToolkit_Maui_Media_WinRT_IPlayReadyMediaEngine<D>::SetSourceFromManifestBytes(param::vector_view<std::uint8_t> const& manifestData, param::hstring const& originalUrl, winrt::CommunityToolkit::Maui::Media::WinRT::PlayReadyDrmConfiguration const& drmConfig) const
    {
        consume_general<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyMediaEngine, D>(static_cast<D const*>(this), &abi_t<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyMediaEngine>::SetSourceFromManifestBytes, *(void**)(&manifestData), *(void**)(&originalUrl), *(void**)(&drmConfig));
    }
    template <typename D> auto consume_CommunityToolkit_Maui_Media_WinRT_IPlayReadyMediaEngine<D>::TestCdmGenerateRequest(param::hstring const& mp4Path, param::hstring const& licenseUrl, param::hstring const& licenseHeaderName, param::hstring const& licenseHeaderValue) const
    {
        void* result{};
        consume_general<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyMediaEngine, D>(static_cast<D const*>(this), &abi_t<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyMediaEngine>::TestCdmGenerateRequest, *(void**)(&mp4Path), *(void**)(&licenseUrl), *(void**)(&licenseHeaderName), *(void**)(&licenseHeaderValue), &result);
        return hstring{ result, take_ownership_from_abi };
    }
    template <typename D> auto consume_CommunityToolkit_Maui_Media_WinRT_IPlayReadyMediaEngine<D>::Play() const
    {
        consume_general<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyMediaEngine, D>(static_cast<D const*>(this), &abi_t<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyMediaEngine>::Play);
    }
    template <typename D> auto consume_CommunityToolkit_Maui_Media_WinRT_IPlayReadyMediaEngine<D>::Pause() const
    {
        consume_general<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyMediaEngine, D>(static_cast<D const*>(this), &abi_t<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyMediaEngine>::Pause);
    }
    template <typename D> auto consume_CommunityToolkit_Maui_Media_WinRT_IPlayReadyMediaEngine<D>::Seek(double positionSeconds) const
    {
        consume_general<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyMediaEngine, D>(static_cast<D const*>(this), &abi_t<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyMediaEngine>::Seek, positionSeconds);
    }
    template <typename D> auto consume_CommunityToolkit_Maui_Media_WinRT_IPlayReadyMediaEngine<D>::SetVolume(double volume) const
    {
        consume_general<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyMediaEngine, D>(static_cast<D const*>(this), &abi_t<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyMediaEngine>::SetVolume, volume);
    }
    template <typename D> auto consume_CommunityToolkit_Maui_Media_WinRT_IPlayReadyMediaEngine<D>::SetMuted(bool muted) const
    {
        consume_general<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyMediaEngine, D>(static_cast<D const*>(this), &abi_t<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyMediaEngine>::SetMuted, muted);
    }
    template <typename D> auto consume_CommunityToolkit_Maui_Media_WinRT_IPlayReadyMediaEngine<D>::SetPlaybackRate(double rate) const
    {
        consume_general<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyMediaEngine, D>(static_cast<D const*>(this), &abi_t<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyMediaEngine>::SetPlaybackRate, rate);
    }
    template <typename D> auto consume_CommunityToolkit_Maui_Media_WinRT_IPlayReadyMediaEngine<D>::SetLooping(bool looping) const
    {
        consume_general<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyMediaEngine, D>(static_cast<D const*>(this), &abi_t<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyMediaEngine>::SetLooping, looping);
    }
    template <typename D> auto consume_CommunityToolkit_Maui_Media_WinRT_IPlayReadyMediaEngine<D>::SetStretch(std::int32_t stretchMode) const
    {
        consume_general<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyMediaEngine, D>(static_cast<D const*>(this), &abi_t<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyMediaEngine>::SetStretch, stretchMode);
    }
    template <typename D> auto consume_CommunityToolkit_Maui_Media_WinRT_IPlayReadyMediaEngine<D>::ResizeSwapChain(std::uint32_t width, std::uint32_t height) const
    {
        consume_general<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyMediaEngine, D>(static_cast<D const*>(this), &abi_t<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyMediaEngine>::ResizeSwapChain, width, height);
    }
    template <typename D> auto consume_CommunityToolkit_Maui_Media_WinRT_IPlayReadyMediaEngine<D>::Close() const
    {
        consume_general<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyMediaEngine, D>(static_cast<D const*>(this), &abi_t<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyMediaEngine>::Close);
    }
    template <typename D> auto consume_CommunityToolkit_Maui_Media_WinRT_IPlayReadyMediaEngine<D>::CurrentPositionSeconds() const
    {
        double value{};
        consume_general<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyMediaEngine, D>(static_cast<D const*>(this), &abi_t<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyMediaEngine>::get_CurrentPositionSeconds, &value);
        return value;
    }
    template <typename D> auto consume_CommunityToolkit_Maui_Media_WinRT_IPlayReadyMediaEngine<D>::DurationSeconds() const
    {
        double value{};
        consume_general<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyMediaEngine, D>(static_cast<D const*>(this), &abi_t<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyMediaEngine>::get_DurationSeconds, &value);
        return value;
    }
    template <typename D> auto consume_CommunityToolkit_Maui_Media_WinRT_IPlayReadyMediaEngine<D>::NaturalVideoWidth() const
    {
        std::uint32_t value{};
        consume_general<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyMediaEngine, D>(static_cast<D const*>(this), &abi_t<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyMediaEngine>::get_NaturalVideoWidth, &value);
        return value;
    }
    template <typename D> auto consume_CommunityToolkit_Maui_Media_WinRT_IPlayReadyMediaEngine<D>::NaturalVideoHeight() const
    {
        std::uint32_t value{};
        consume_general<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyMediaEngine, D>(static_cast<D const*>(this), &abi_t<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyMediaEngine>::get_NaturalVideoHeight, &value);
        return value;
    }
    template <typename D> auto consume_CommunityToolkit_Maui_Media_WinRT_IPlayReadyMediaEngine<D>::IsBuffering() const
    {
        bool value{};
        consume_general<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyMediaEngine, D>(static_cast<D const*>(this), &abi_t<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyMediaEngine>::get_IsBuffering, &value);
        return value;
    }
    template <typename D> auto consume_CommunityToolkit_Maui_Media_WinRT_IPlayReadyMediaEngine<D>::MediaOpened(winrt::Windows::Foundation::TypedEventHandler<winrt::CommunityToolkit::Maui::Media::WinRT::PlayReadyMediaEngine, winrt::Windows::Foundation::IInspectable> const& handler) const
    {
        winrt::event_token token{};
        consume_general<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyMediaEngine, D>(static_cast<D const*>(this), &abi_t<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyMediaEngine>::add_MediaOpened, *(void**)(&handler), put_abi(token));
        return token;
    }
    template <typename D> auto consume_CommunityToolkit_Maui_Media_WinRT_IPlayReadyMediaEngine<D>::MediaOpened(auto_revoke_t, winrt::Windows::Foundation::TypedEventHandler<winrt::CommunityToolkit::Maui::Media::WinRT::PlayReadyMediaEngine, winrt::Windows::Foundation::IInspectable> const& handler) const
    {
        return impl::make_event_revoker<D, MediaOpened_revoker>(this, MediaOpened(handler));
    }
    template <typename D> auto consume_CommunityToolkit_Maui_Media_WinRT_IPlayReadyMediaEngine<D>::MediaOpened(winrt::event_token const& token) const noexcept
    {
        consume_noexcept_remove_overload<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyMediaEngine, D>(static_cast<D const*>(this), &abi_t<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyMediaEngine>::remove_MediaOpened, impl::bind_in(token));
    }
    template <typename D> auto consume_CommunityToolkit_Maui_Media_WinRT_IPlayReadyMediaEngine<D>::MediaFailed(winrt::Windows::Foundation::TypedEventHandler<winrt::CommunityToolkit::Maui::Media::WinRT::PlayReadyMediaEngine, winrt::CommunityToolkit::Maui::Media::WinRT::MediaEngineErrorEventArgs> const& handler) const
    {
        winrt::event_token token{};
        consume_general<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyMediaEngine, D>(static_cast<D const*>(this), &abi_t<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyMediaEngine>::add_MediaFailed, *(void**)(&handler), put_abi(token));
        return token;
    }
    template <typename D> auto consume_CommunityToolkit_Maui_Media_WinRT_IPlayReadyMediaEngine<D>::MediaFailed(auto_revoke_t, winrt::Windows::Foundation::TypedEventHandler<winrt::CommunityToolkit::Maui::Media::WinRT::PlayReadyMediaEngine, winrt::CommunityToolkit::Maui::Media::WinRT::MediaEngineErrorEventArgs> const& handler) const
    {
        return impl::make_event_revoker<D, MediaFailed_revoker>(this, MediaFailed(handler));
    }
    template <typename D> auto consume_CommunityToolkit_Maui_Media_WinRT_IPlayReadyMediaEngine<D>::MediaFailed(winrt::event_token const& token) const noexcept
    {
        consume_noexcept_remove_overload<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyMediaEngine, D>(static_cast<D const*>(this), &abi_t<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyMediaEngine>::remove_MediaFailed, impl::bind_in(token));
    }
    template <typename D> auto consume_CommunityToolkit_Maui_Media_WinRT_IPlayReadyMediaEngine<D>::MediaEnded(winrt::Windows::Foundation::TypedEventHandler<winrt::CommunityToolkit::Maui::Media::WinRT::PlayReadyMediaEngine, winrt::Windows::Foundation::IInspectable> const& handler) const
    {
        winrt::event_token token{};
        consume_general<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyMediaEngine, D>(static_cast<D const*>(this), &abi_t<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyMediaEngine>::add_MediaEnded, *(void**)(&handler), put_abi(token));
        return token;
    }
    template <typename D> auto consume_CommunityToolkit_Maui_Media_WinRT_IPlayReadyMediaEngine<D>::MediaEnded(auto_revoke_t, winrt::Windows::Foundation::TypedEventHandler<winrt::CommunityToolkit::Maui::Media::WinRT::PlayReadyMediaEngine, winrt::Windows::Foundation::IInspectable> const& handler) const
    {
        return impl::make_event_revoker<D, MediaEnded_revoker>(this, MediaEnded(handler));
    }
    template <typename D> auto consume_CommunityToolkit_Maui_Media_WinRT_IPlayReadyMediaEngine<D>::MediaEnded(winrt::event_token const& token) const noexcept
    {
        consume_noexcept_remove_overload<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyMediaEngine, D>(static_cast<D const*>(this), &abi_t<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyMediaEngine>::remove_MediaEnded, impl::bind_in(token));
    }
    template <typename D> auto consume_CommunityToolkit_Maui_Media_WinRT_IPlayReadyMediaEngine<D>::TimeChanged(winrt::Windows::Foundation::TypedEventHandler<winrt::CommunityToolkit::Maui::Media::WinRT::PlayReadyMediaEngine, winrt::CommunityToolkit::Maui::Media::WinRT::MediaEngineTimeChangedEventArgs> const& handler) const
    {
        winrt::event_token token{};
        consume_general<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyMediaEngine, D>(static_cast<D const*>(this), &abi_t<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyMediaEngine>::add_TimeChanged, *(void**)(&handler), put_abi(token));
        return token;
    }
    template <typename D> auto consume_CommunityToolkit_Maui_Media_WinRT_IPlayReadyMediaEngine<D>::TimeChanged(auto_revoke_t, winrt::Windows::Foundation::TypedEventHandler<winrt::CommunityToolkit::Maui::Media::WinRT::PlayReadyMediaEngine, winrt::CommunityToolkit::Maui::Media::WinRT::MediaEngineTimeChangedEventArgs> const& handler) const
    {
        return impl::make_event_revoker<D, TimeChanged_revoker>(this, TimeChanged(handler));
    }
    template <typename D> auto consume_CommunityToolkit_Maui_Media_WinRT_IPlayReadyMediaEngine<D>::TimeChanged(winrt::event_token const& token) const noexcept
    {
        consume_noexcept_remove_overload<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyMediaEngine, D>(static_cast<D const*>(this), &abi_t<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyMediaEngine>::remove_TimeChanged, impl::bind_in(token));
    }
    template <typename D> auto consume_CommunityToolkit_Maui_Media_WinRT_IPlayReadyMediaEngine<D>::BufferingChanged(winrt::Windows::Foundation::TypedEventHandler<winrt::CommunityToolkit::Maui::Media::WinRT::PlayReadyMediaEngine, bool> const& handler) const
    {
        winrt::event_token token{};
        consume_general<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyMediaEngine, D>(static_cast<D const*>(this), &abi_t<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyMediaEngine>::add_BufferingChanged, *(void**)(&handler), put_abi(token));
        return token;
    }
    template <typename D> auto consume_CommunityToolkit_Maui_Media_WinRT_IPlayReadyMediaEngine<D>::BufferingChanged(auto_revoke_t, winrt::Windows::Foundation::TypedEventHandler<winrt::CommunityToolkit::Maui::Media::WinRT::PlayReadyMediaEngine, bool> const& handler) const
    {
        return impl::make_event_revoker<D, BufferingChanged_revoker>(this, BufferingChanged(handler));
    }
    template <typename D> auto consume_CommunityToolkit_Maui_Media_WinRT_IPlayReadyMediaEngine<D>::BufferingChanged(winrt::event_token const& token) const noexcept
    {
        consume_noexcept_remove_overload<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyMediaEngine, D>(static_cast<D const*>(this), &abi_t<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyMediaEngine>::remove_BufferingChanged, impl::bind_in(token));
    }
    template <typename D> auto consume_CommunityToolkit_Maui_Media_WinRT_IPlayReadyMediaEngine<D>::SizeChanged(winrt::Windows::Foundation::TypedEventHandler<winrt::CommunityToolkit::Maui::Media::WinRT::PlayReadyMediaEngine, winrt::CommunityToolkit::Maui::Media::WinRT::MediaEngineSizeChangedEventArgs> const& handler) const
    {
        winrt::event_token token{};
        consume_general<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyMediaEngine, D>(static_cast<D const*>(this), &abi_t<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyMediaEngine>::add_SizeChanged, *(void**)(&handler), put_abi(token));
        return token;
    }
    template <typename D> auto consume_CommunityToolkit_Maui_Media_WinRT_IPlayReadyMediaEngine<D>::SizeChanged(auto_revoke_t, winrt::Windows::Foundation::TypedEventHandler<winrt::CommunityToolkit::Maui::Media::WinRT::PlayReadyMediaEngine, winrt::CommunityToolkit::Maui::Media::WinRT::MediaEngineSizeChangedEventArgs> const& handler) const
    {
        return impl::make_event_revoker<D, SizeChanged_revoker>(this, SizeChanged(handler));
    }
    template <typename D> auto consume_CommunityToolkit_Maui_Media_WinRT_IPlayReadyMediaEngine<D>::SizeChanged(winrt::event_token const& token) const noexcept
    {
        consume_noexcept_remove_overload<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyMediaEngine, D>(static_cast<D const*>(this), &abi_t<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyMediaEngine>::remove_SizeChanged, impl::bind_in(token));
    }
    template <typename D> auto consume_CommunityToolkit_Maui_Media_WinRT_IPlayReadyMediaEngine<D>::LicenseAcquired(winrt::Windows::Foundation::TypedEventHandler<winrt::CommunityToolkit::Maui::Media::WinRT::PlayReadyMediaEngine, winrt::CommunityToolkit::Maui::Media::WinRT::DrmLicenseAcquiredEventArgs> const& handler) const
    {
        winrt::event_token token{};
        consume_general<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyMediaEngine, D>(static_cast<D const*>(this), &abi_t<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyMediaEngine>::add_LicenseAcquired, *(void**)(&handler), put_abi(token));
        return token;
    }
    template <typename D> auto consume_CommunityToolkit_Maui_Media_WinRT_IPlayReadyMediaEngine<D>::LicenseAcquired(auto_revoke_t, winrt::Windows::Foundation::TypedEventHandler<winrt::CommunityToolkit::Maui::Media::WinRT::PlayReadyMediaEngine, winrt::CommunityToolkit::Maui::Media::WinRT::DrmLicenseAcquiredEventArgs> const& handler) const
    {
        return impl::make_event_revoker<D, LicenseAcquired_revoker>(this, LicenseAcquired(handler));
    }
    template <typename D> auto consume_CommunityToolkit_Maui_Media_WinRT_IPlayReadyMediaEngine<D>::LicenseAcquired(winrt::event_token const& token) const noexcept
    {
        consume_noexcept_remove_overload<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyMediaEngine, D>(static_cast<D const*>(this), &abi_t<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyMediaEngine>::remove_LicenseAcquired, impl::bind_in(token));
    }
    template <typename D> auto consume_CommunityToolkit_Maui_Media_WinRT_IPlayReadyMediaEngine<D>::StateChanged(winrt::Windows::Foundation::TypedEventHandler<winrt::CommunityToolkit::Maui::Media::WinRT::PlayReadyMediaEngine, winrt::CommunityToolkit::Maui::Media::WinRT::MediaEngineStateChangedEventArgs> const& handler) const
    {
        winrt::event_token token{};
        consume_general<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyMediaEngine, D>(static_cast<D const*>(this), &abi_t<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyMediaEngine>::add_StateChanged, *(void**)(&handler), put_abi(token));
        return token;
    }
    template <typename D> auto consume_CommunityToolkit_Maui_Media_WinRT_IPlayReadyMediaEngine<D>::StateChanged(auto_revoke_t, winrt::Windows::Foundation::TypedEventHandler<winrt::CommunityToolkit::Maui::Media::WinRT::PlayReadyMediaEngine, winrt::CommunityToolkit::Maui::Media::WinRT::MediaEngineStateChangedEventArgs> const& handler) const
    {
        return impl::make_event_revoker<D, StateChanged_revoker>(this, StateChanged(handler));
    }
    template <typename D> auto consume_CommunityToolkit_Maui_Media_WinRT_IPlayReadyMediaEngine<D>::StateChanged(winrt::event_token const& token) const noexcept
    {
        consume_noexcept_remove_overload<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyMediaEngine, D>(static_cast<D const*>(this), &abi_t<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyMediaEngine>::remove_StateChanged, impl::bind_in(token));
    }
    template <typename D>
    struct produce<D, winrt::CommunityToolkit::Maui::Media::WinRT::IDrmLicenseAcquiredEventArgs> : produce_base<D, winrt::CommunityToolkit::Maui::Media::WinRT::IDrmLicenseAcquiredEventArgs>
    {
        std::int32_t __stdcall get_Success(bool* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *value = detach_from<bool>(this->shim().Success());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_ErrorMessage(void** value) noexcept final try
        {
            clear_abi(value);
            typename D::abi_guard guard(this->shim());
            *value = detach_from<hstring>(this->shim().ErrorMessage());
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
    template <typename D>
    struct produce<D, winrt::CommunityToolkit::Maui::Media::WinRT::IDrmLicenseAcquiredEventArgsFactory> : produce_base<D, winrt::CommunityToolkit::Maui::Media::WinRT::IDrmLicenseAcquiredEventArgsFactory>
    {
        std::int32_t __stdcall CreateInstance(bool success, void* errorMessage, void** value) noexcept final try
        {
            clear_abi(value);
            typename D::abi_guard guard(this->shim());
            *value = detach_from<winrt::CommunityToolkit::Maui::Media::WinRT::DrmLicenseAcquiredEventArgs>(this->shim().CreateInstance(success, *reinterpret_cast<hstring const*>(&errorMessage)));
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
    template <typename D>
    struct produce<D, winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineErrorEventArgs> : produce_base<D, winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineErrorEventArgs>
    {
        std::int32_t __stdcall get_ErrorCode(std::int32_t* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *value = detach_from<std::int32_t>(this->shim().ErrorCode());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_ErrorMessage(void** value) noexcept final try
        {
            clear_abi(value);
            typename D::abi_guard guard(this->shim());
            *value = detach_from<hstring>(this->shim().ErrorMessage());
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
    template <typename D>
    struct produce<D, winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineErrorEventArgsFactory> : produce_base<D, winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineErrorEventArgsFactory>
    {
        std::int32_t __stdcall CreateInstance(std::int32_t errorCode, void* errorMessage, void** value) noexcept final try
        {
            clear_abi(value);
            typename D::abi_guard guard(this->shim());
            *value = detach_from<winrt::CommunityToolkit::Maui::Media::WinRT::MediaEngineErrorEventArgs>(this->shim().CreateInstance(errorCode, *reinterpret_cast<hstring const*>(&errorMessage)));
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
    template <typename D>
    struct produce<D, winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineSizeChangedEventArgs> : produce_base<D, winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineSizeChangedEventArgs>
    {
        std::int32_t __stdcall get_Width(std::uint32_t* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *value = detach_from<std::uint32_t>(this->shim().Width());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_Height(std::uint32_t* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *value = detach_from<std::uint32_t>(this->shim().Height());
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
    template <typename D>
    struct produce<D, winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineSizeChangedEventArgsFactory> : produce_base<D, winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineSizeChangedEventArgsFactory>
    {
        std::int32_t __stdcall CreateInstance(std::uint32_t width, std::uint32_t height, void** value) noexcept final try
        {
            clear_abi(value);
            typename D::abi_guard guard(this->shim());
            *value = detach_from<winrt::CommunityToolkit::Maui::Media::WinRT::MediaEngineSizeChangedEventArgs>(this->shim().CreateInstance(width, height));
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
    template <typename D>
    struct produce<D, winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineStateChangedEventArgs> : produce_base<D, winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineStateChangedEventArgs>
    {
        std::int32_t __stdcall get_OldState(std::int32_t* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *value = detach_from<std::int32_t>(this->shim().OldState());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_NewState(std::int32_t* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *value = detach_from<std::int32_t>(this->shim().NewState());
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
    template <typename D>
    struct produce<D, winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineStateChangedEventArgsFactory> : produce_base<D, winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineStateChangedEventArgsFactory>
    {
        std::int32_t __stdcall CreateInstance(std::int32_t oldState, std::int32_t newState, void** value) noexcept final try
        {
            clear_abi(value);
            typename D::abi_guard guard(this->shim());
            *value = detach_from<winrt::CommunityToolkit::Maui::Media::WinRT::MediaEngineStateChangedEventArgs>(this->shim().CreateInstance(oldState, newState));
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
    template <typename D>
    struct produce<D, winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineTimeChangedEventArgs> : produce_base<D, winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineTimeChangedEventArgs>
    {
        std::int32_t __stdcall get_PositionSeconds(double* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *value = detach_from<double>(this->shim().PositionSeconds());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_DurationSeconds(double* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *value = detach_from<double>(this->shim().DurationSeconds());
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
    template <typename D>
    struct produce<D, winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineTimeChangedEventArgsFactory> : produce_base<D, winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineTimeChangedEventArgsFactory>
    {
        std::int32_t __stdcall CreateInstance(double positionSeconds, double durationSeconds, void** value) noexcept final try
        {
            clear_abi(value);
            typename D::abi_guard guard(this->shim());
            *value = detach_from<winrt::CommunityToolkit::Maui::Media::WinRT::MediaEngineTimeChangedEventArgs>(this->shim().CreateInstance(positionSeconds, durationSeconds));
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
    template <typename D>
    struct produce<D, winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyDrmConfiguration> : produce_base<D, winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyDrmConfiguration>
    {
        std::int32_t __stdcall get_LicenseServerUrl(void** value) noexcept final try
        {
            clear_abi(value);
            typename D::abi_guard guard(this->shim());
            *value = detach_from<hstring>(this->shim().LicenseServerUrl());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall put_LicenseServerUrl(void* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().LicenseServerUrl(*reinterpret_cast<hstring const*>(&value));
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_CustomHeaders(void** value) noexcept final try
        {
            clear_abi(value);
            typename D::abi_guard guard(this->shim());
            *value = detach_from<winrt::Windows::Foundation::Collections::IMap<hstring, hstring>>(this->shim().CustomHeaders());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall put_CustomHeaders(void* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().CustomHeaders(*reinterpret_cast<winrt::Windows::Foundation::Collections::IMap<hstring, hstring> const*>(&value));
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
    template <typename D>
    struct produce<D, winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyMediaEngine> : produce_base<D, winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyMediaEngine>
    {
        std::int32_t __stdcall Initialize(std::int64_t swapChainPanelHandle) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().Initialize(swapChainPanelHandle);
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall SetSource(void* url, void* drmConfig) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().SetSource(*reinterpret_cast<hstring const*>(&url), *reinterpret_cast<winrt::CommunityToolkit::Maui::Media::WinRT::PlayReadyDrmConfiguration const*>(&drmConfig));
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall SetSourceFromManifestBytes(void* manifestData, void* originalUrl, void* drmConfig) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().SetSourceFromManifestBytes(*reinterpret_cast<winrt::Windows::Foundation::Collections::IVectorView<std::uint8_t> const*>(&manifestData), *reinterpret_cast<hstring const*>(&originalUrl), *reinterpret_cast<winrt::CommunityToolkit::Maui::Media::WinRT::PlayReadyDrmConfiguration const*>(&drmConfig));
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall TestCdmGenerateRequest(void* mp4Path, void* licenseUrl, void* licenseHeaderName, void* licenseHeaderValue, void** result) noexcept final try
        {
            clear_abi(result);
            typename D::abi_guard guard(this->shim());
            *result = detach_from<hstring>(this->shim().TestCdmGenerateRequest(*reinterpret_cast<hstring const*>(&mp4Path), *reinterpret_cast<hstring const*>(&licenseUrl), *reinterpret_cast<hstring const*>(&licenseHeaderName), *reinterpret_cast<hstring const*>(&licenseHeaderValue)));
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall Play() noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().Play();
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall Pause() noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().Pause();
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall Seek(double positionSeconds) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().Seek(positionSeconds);
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall SetVolume(double volume) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().SetVolume(volume);
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall SetMuted(bool muted) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().SetMuted(muted);
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall SetPlaybackRate(double rate) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().SetPlaybackRate(rate);
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall SetLooping(bool looping) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().SetLooping(looping);
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall SetStretch(std::int32_t stretchMode) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().SetStretch(stretchMode);
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall ResizeSwapChain(std::uint32_t width, std::uint32_t height) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().ResizeSwapChain(width, height);
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall Close() noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().Close();
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_CurrentPositionSeconds(double* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *value = detach_from<double>(this->shim().CurrentPositionSeconds());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_DurationSeconds(double* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *value = detach_from<double>(this->shim().DurationSeconds());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_NaturalVideoWidth(std::uint32_t* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *value = detach_from<std::uint32_t>(this->shim().NaturalVideoWidth());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_NaturalVideoHeight(std::uint32_t* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *value = detach_from<std::uint32_t>(this->shim().NaturalVideoHeight());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_IsBuffering(bool* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *value = detach_from<bool>(this->shim().IsBuffering());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall add_MediaOpened(void* handler, winrt::event_token* token) noexcept final try
        {
            zero_abi<winrt::event_token>(token);
            typename D::abi_guard guard(this->shim());
            *token = detach_from<winrt::event_token>(this->shim().MediaOpened(*reinterpret_cast<winrt::Windows::Foundation::TypedEventHandler<winrt::CommunityToolkit::Maui::Media::WinRT::PlayReadyMediaEngine, winrt::Windows::Foundation::IInspectable> const*>(&handler)));
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall remove_MediaOpened(winrt::event_token token) noexcept final
        {
            typename D::abi_guard guard(this->shim());
            this->shim().MediaOpened(*reinterpret_cast<winrt::event_token const*>(&token));
            return 0;
        }
        std::int32_t __stdcall add_MediaFailed(void* handler, winrt::event_token* token) noexcept final try
        {
            zero_abi<winrt::event_token>(token);
            typename D::abi_guard guard(this->shim());
            *token = detach_from<winrt::event_token>(this->shim().MediaFailed(*reinterpret_cast<winrt::Windows::Foundation::TypedEventHandler<winrt::CommunityToolkit::Maui::Media::WinRT::PlayReadyMediaEngine, winrt::CommunityToolkit::Maui::Media::WinRT::MediaEngineErrorEventArgs> const*>(&handler)));
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall remove_MediaFailed(winrt::event_token token) noexcept final
        {
            typename D::abi_guard guard(this->shim());
            this->shim().MediaFailed(*reinterpret_cast<winrt::event_token const*>(&token));
            return 0;
        }
        std::int32_t __stdcall add_MediaEnded(void* handler, winrt::event_token* token) noexcept final try
        {
            zero_abi<winrt::event_token>(token);
            typename D::abi_guard guard(this->shim());
            *token = detach_from<winrt::event_token>(this->shim().MediaEnded(*reinterpret_cast<winrt::Windows::Foundation::TypedEventHandler<winrt::CommunityToolkit::Maui::Media::WinRT::PlayReadyMediaEngine, winrt::Windows::Foundation::IInspectable> const*>(&handler)));
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall remove_MediaEnded(winrt::event_token token) noexcept final
        {
            typename D::abi_guard guard(this->shim());
            this->shim().MediaEnded(*reinterpret_cast<winrt::event_token const*>(&token));
            return 0;
        }
        std::int32_t __stdcall add_TimeChanged(void* handler, winrt::event_token* token) noexcept final try
        {
            zero_abi<winrt::event_token>(token);
            typename D::abi_guard guard(this->shim());
            *token = detach_from<winrt::event_token>(this->shim().TimeChanged(*reinterpret_cast<winrt::Windows::Foundation::TypedEventHandler<winrt::CommunityToolkit::Maui::Media::WinRT::PlayReadyMediaEngine, winrt::CommunityToolkit::Maui::Media::WinRT::MediaEngineTimeChangedEventArgs> const*>(&handler)));
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall remove_TimeChanged(winrt::event_token token) noexcept final
        {
            typename D::abi_guard guard(this->shim());
            this->shim().TimeChanged(*reinterpret_cast<winrt::event_token const*>(&token));
            return 0;
        }
        std::int32_t __stdcall add_BufferingChanged(void* handler, winrt::event_token* token) noexcept final try
        {
            zero_abi<winrt::event_token>(token);
            typename D::abi_guard guard(this->shim());
            *token = detach_from<winrt::event_token>(this->shim().BufferingChanged(*reinterpret_cast<winrt::Windows::Foundation::TypedEventHandler<winrt::CommunityToolkit::Maui::Media::WinRT::PlayReadyMediaEngine, bool> const*>(&handler)));
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall remove_BufferingChanged(winrt::event_token token) noexcept final
        {
            typename D::abi_guard guard(this->shim());
            this->shim().BufferingChanged(*reinterpret_cast<winrt::event_token const*>(&token));
            return 0;
        }
        std::int32_t __stdcall add_SizeChanged(void* handler, winrt::event_token* token) noexcept final try
        {
            zero_abi<winrt::event_token>(token);
            typename D::abi_guard guard(this->shim());
            *token = detach_from<winrt::event_token>(this->shim().SizeChanged(*reinterpret_cast<winrt::Windows::Foundation::TypedEventHandler<winrt::CommunityToolkit::Maui::Media::WinRT::PlayReadyMediaEngine, winrt::CommunityToolkit::Maui::Media::WinRT::MediaEngineSizeChangedEventArgs> const*>(&handler)));
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall remove_SizeChanged(winrt::event_token token) noexcept final
        {
            typename D::abi_guard guard(this->shim());
            this->shim().SizeChanged(*reinterpret_cast<winrt::event_token const*>(&token));
            return 0;
        }
        std::int32_t __stdcall add_LicenseAcquired(void* handler, winrt::event_token* token) noexcept final try
        {
            zero_abi<winrt::event_token>(token);
            typename D::abi_guard guard(this->shim());
            *token = detach_from<winrt::event_token>(this->shim().LicenseAcquired(*reinterpret_cast<winrt::Windows::Foundation::TypedEventHandler<winrt::CommunityToolkit::Maui::Media::WinRT::PlayReadyMediaEngine, winrt::CommunityToolkit::Maui::Media::WinRT::DrmLicenseAcquiredEventArgs> const*>(&handler)));
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall remove_LicenseAcquired(winrt::event_token token) noexcept final
        {
            typename D::abi_guard guard(this->shim());
            this->shim().LicenseAcquired(*reinterpret_cast<winrt::event_token const*>(&token));
            return 0;
        }
        std::int32_t __stdcall add_StateChanged(void* handler, winrt::event_token* token) noexcept final try
        {
            zero_abi<winrt::event_token>(token);
            typename D::abi_guard guard(this->shim());
            *token = detach_from<winrt::event_token>(this->shim().StateChanged(*reinterpret_cast<winrt::Windows::Foundation::TypedEventHandler<winrt::CommunityToolkit::Maui::Media::WinRT::PlayReadyMediaEngine, winrt::CommunityToolkit::Maui::Media::WinRT::MediaEngineStateChangedEventArgs> const*>(&handler)));
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall remove_StateChanged(winrt::event_token token) noexcept final
        {
            typename D::abi_guard guard(this->shim());
            this->shim().StateChanged(*reinterpret_cast<winrt::event_token const*>(&token));
            return 0;
        }
    };
}
WINRT_EXPORT namespace winrt::CommunityToolkit::Maui::Media::WinRT
{
}
namespace std
{
#ifndef WINRT_LEAN_AND_MEAN
    template<> struct hash<winrt::CommunityToolkit::Maui::Media::WinRT::IDrmLicenseAcquiredEventArgs> : winrt::impl::hash_base {};
    template<> struct hash<winrt::CommunityToolkit::Maui::Media::WinRT::IDrmLicenseAcquiredEventArgsFactory> : winrt::impl::hash_base {};
    template<> struct hash<winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineErrorEventArgs> : winrt::impl::hash_base {};
    template<> struct hash<winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineErrorEventArgsFactory> : winrt::impl::hash_base {};
    template<> struct hash<winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineSizeChangedEventArgs> : winrt::impl::hash_base {};
    template<> struct hash<winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineSizeChangedEventArgsFactory> : winrt::impl::hash_base {};
    template<> struct hash<winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineStateChangedEventArgs> : winrt::impl::hash_base {};
    template<> struct hash<winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineStateChangedEventArgsFactory> : winrt::impl::hash_base {};
    template<> struct hash<winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineTimeChangedEventArgs> : winrt::impl::hash_base {};
    template<> struct hash<winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineTimeChangedEventArgsFactory> : winrt::impl::hash_base {};
    template<> struct hash<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyDrmConfiguration> : winrt::impl::hash_base {};
    template<> struct hash<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyMediaEngine> : winrt::impl::hash_base {};
    template<> struct hash<winrt::CommunityToolkit::Maui::Media::WinRT::DrmLicenseAcquiredEventArgs> : winrt::impl::hash_base {};
    template<> struct hash<winrt::CommunityToolkit::Maui::Media::WinRT::MediaEngineErrorEventArgs> : winrt::impl::hash_base {};
    template<> struct hash<winrt::CommunityToolkit::Maui::Media::WinRT::MediaEngineSizeChangedEventArgs> : winrt::impl::hash_base {};
    template<> struct hash<winrt::CommunityToolkit::Maui::Media::WinRT::MediaEngineStateChangedEventArgs> : winrt::impl::hash_base {};
    template<> struct hash<winrt::CommunityToolkit::Maui::Media::WinRT::MediaEngineTimeChangedEventArgs> : winrt::impl::hash_base {};
    template<> struct hash<winrt::CommunityToolkit::Maui::Media::WinRT::PlayReadyDrmConfiguration> : winrt::impl::hash_base {};
    template<> struct hash<winrt::CommunityToolkit::Maui::Media::WinRT::PlayReadyMediaEngine> : winrt::impl::hash_base {};
#endif // WINRT_LEAN_AND_MEAN
#ifdef __cpp_lib_format
#endif // __cpp_lib_format
}
#endif
#endif // WINRT_IMPORT_MODULE
