// WARNING: Please don't edit this file. It was generated by C++/WinRT v3.0.260715.1

#pragma once
#ifndef WINRT_CommunityToolkit_Maui_Media_WinRT_0_H
#define WINRT_CommunityToolkit_Maui_Media_WinRT_0_H
WINRT_EXPORT namespace winrt::Windows::Foundation
{
    struct EventRegistrationToken;
    template <typename TSender, typename TResult> struct WINRT_IMPL_EMPTY_BASES TypedEventHandler;
}
WINRT_EXPORT namespace winrt::Windows::Foundation::Collections
{
    template <typename K, typename V> struct WINRT_IMPL_EMPTY_BASES IMap;
    template <typename T> struct WINRT_IMPL_EMPTY_BASES IVectorView;
}
WINRT_EXPORT namespace winrt::CommunityToolkit::Maui::Media::WinRT
{
    struct IDrmLicenseAcquiredEventArgs;
    struct IDrmLicenseAcquiredEventArgsFactory;
    struct IMediaEngineErrorEventArgs;
    struct IMediaEngineErrorEventArgsFactory;
    struct IMediaEngineSizeChangedEventArgs;
    struct IMediaEngineSizeChangedEventArgsFactory;
    struct IMediaEngineStateChangedEventArgs;
    struct IMediaEngineStateChangedEventArgsFactory;
    struct IMediaEngineTimeChangedEventArgs;
    struct IMediaEngineTimeChangedEventArgsFactory;
    struct IPlayReadyDrmConfiguration;
    struct IPlayReadyMediaEngine;
    struct DrmLicenseAcquiredEventArgs;
    struct MediaEngineErrorEventArgs;
    struct MediaEngineSizeChangedEventArgs;
    struct MediaEngineStateChangedEventArgs;
    struct MediaEngineTimeChangedEventArgs;
    struct PlayReadyDrmConfiguration;
    struct PlayReadyMediaEngine;
}
WINRT_EXPORT namespace winrt::impl
{
    template <> struct category<winrt::CommunityToolkit::Maui::Media::WinRT::IDrmLicenseAcquiredEventArgs>{ using type = interface_category; };
    template <> struct category<winrt::CommunityToolkit::Maui::Media::WinRT::IDrmLicenseAcquiredEventArgsFactory>{ using type = interface_category; };
    template <> struct category<winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineErrorEventArgs>{ using type = interface_category; };
    template <> struct category<winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineErrorEventArgsFactory>{ using type = interface_category; };
    template <> struct category<winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineSizeChangedEventArgs>{ using type = interface_category; };
    template <> struct category<winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineSizeChangedEventArgsFactory>{ using type = interface_category; };
    template <> struct category<winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineStateChangedEventArgs>{ using type = interface_category; };
    template <> struct category<winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineStateChangedEventArgsFactory>{ using type = interface_category; };
    template <> struct category<winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineTimeChangedEventArgs>{ using type = interface_category; };
    template <> struct category<winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineTimeChangedEventArgsFactory>{ using type = interface_category; };
    template <> struct category<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyDrmConfiguration>{ using type = interface_category; };
    template <> struct category<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyMediaEngine>{ using type = interface_category; };
    template <> struct category<winrt::CommunityToolkit::Maui::Media::WinRT::DrmLicenseAcquiredEventArgs>{ using type = class_category; };
    template <> struct category<winrt::CommunityToolkit::Maui::Media::WinRT::MediaEngineErrorEventArgs>{ using type = class_category; };
    template <> struct category<winrt::CommunityToolkit::Maui::Media::WinRT::MediaEngineSizeChangedEventArgs>{ using type = class_category; };
    template <> struct category<winrt::CommunityToolkit::Maui::Media::WinRT::MediaEngineStateChangedEventArgs>{ using type = class_category; };
    template <> struct category<winrt::CommunityToolkit::Maui::Media::WinRT::MediaEngineTimeChangedEventArgs>{ using type = class_category; };
    template <> struct category<winrt::CommunityToolkit::Maui::Media::WinRT::PlayReadyDrmConfiguration>{ using type = class_category; };
    template <> struct category<winrt::CommunityToolkit::Maui::Media::WinRT::PlayReadyMediaEngine>{ using type = class_category; };
    template <> inline constexpr auto& name_v<winrt::CommunityToolkit::Maui::Media::WinRT::DrmLicenseAcquiredEventArgs> = L"CommunityToolkit.Maui.Media.WinRT.DrmLicenseAcquiredEventArgs";
    template <> inline constexpr auto& name_v<winrt::CommunityToolkit::Maui::Media::WinRT::MediaEngineErrorEventArgs> = L"CommunityToolkit.Maui.Media.WinRT.MediaEngineErrorEventArgs";
    template <> inline constexpr auto& name_v<winrt::CommunityToolkit::Maui::Media::WinRT::MediaEngineSizeChangedEventArgs> = L"CommunityToolkit.Maui.Media.WinRT.MediaEngineSizeChangedEventArgs";
    template <> inline constexpr auto& name_v<winrt::CommunityToolkit::Maui::Media::WinRT::MediaEngineStateChangedEventArgs> = L"CommunityToolkit.Maui.Media.WinRT.MediaEngineStateChangedEventArgs";
    template <> inline constexpr auto& name_v<winrt::CommunityToolkit::Maui::Media::WinRT::MediaEngineTimeChangedEventArgs> = L"CommunityToolkit.Maui.Media.WinRT.MediaEngineTimeChangedEventArgs";
    template <> inline constexpr auto& name_v<winrt::CommunityToolkit::Maui::Media::WinRT::PlayReadyDrmConfiguration> = L"CommunityToolkit.Maui.Media.WinRT.PlayReadyDrmConfiguration";
    template <> inline constexpr auto& name_v<winrt::CommunityToolkit::Maui::Media::WinRT::PlayReadyMediaEngine> = L"CommunityToolkit.Maui.Media.WinRT.PlayReadyMediaEngine";
    template <> inline constexpr auto& name_v<winrt::CommunityToolkit::Maui::Media::WinRT::IDrmLicenseAcquiredEventArgs> = L"CommunityToolkit.Maui.Media.WinRT.IDrmLicenseAcquiredEventArgs";
    template <> inline constexpr auto& name_v<winrt::CommunityToolkit::Maui::Media::WinRT::IDrmLicenseAcquiredEventArgsFactory> = L"CommunityToolkit.Maui.Media.WinRT.IDrmLicenseAcquiredEventArgsFactory";
    template <> inline constexpr auto& name_v<winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineErrorEventArgs> = L"CommunityToolkit.Maui.Media.WinRT.IMediaEngineErrorEventArgs";
    template <> inline constexpr auto& name_v<winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineErrorEventArgsFactory> = L"CommunityToolkit.Maui.Media.WinRT.IMediaEngineErrorEventArgsFactory";
    template <> inline constexpr auto& name_v<winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineSizeChangedEventArgs> = L"CommunityToolkit.Maui.Media.WinRT.IMediaEngineSizeChangedEventArgs";
    template <> inline constexpr auto& name_v<winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineSizeChangedEventArgsFactory> = L"CommunityToolkit.Maui.Media.WinRT.IMediaEngineSizeChangedEventArgsFactory";
    template <> inline constexpr auto& name_v<winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineStateChangedEventArgs> = L"CommunityToolkit.Maui.Media.WinRT.IMediaEngineStateChangedEventArgs";
    template <> inline constexpr auto& name_v<winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineStateChangedEventArgsFactory> = L"CommunityToolkit.Maui.Media.WinRT.IMediaEngineStateChangedEventArgsFactory";
    template <> inline constexpr auto& name_v<winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineTimeChangedEventArgs> = L"CommunityToolkit.Maui.Media.WinRT.IMediaEngineTimeChangedEventArgs";
    template <> inline constexpr auto& name_v<winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineTimeChangedEventArgsFactory> = L"CommunityToolkit.Maui.Media.WinRT.IMediaEngineTimeChangedEventArgsFactory";
    template <> inline constexpr auto& name_v<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyDrmConfiguration> = L"CommunityToolkit.Maui.Media.WinRT.IPlayReadyDrmConfiguration";
    template <> inline constexpr auto& name_v<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyMediaEngine> = L"CommunityToolkit.Maui.Media.WinRT.IPlayReadyMediaEngine";
    template <> inline constexpr guid guid_v<winrt::CommunityToolkit::Maui::Media::WinRT::IDrmLicenseAcquiredEventArgs>{ 0x844724E6,0x73B2,0x5BDD,{ 0x8C,0xE9,0x95,0x72,0xB0,0x02,0xB8,0x55 } }; // 844724E6-73B2-5BDD-8CE9-9572B002B855
    template <> inline constexpr guid guid_v<winrt::CommunityToolkit::Maui::Media::WinRT::IDrmLicenseAcquiredEventArgsFactory>{ 0x9AFF49D5,0x4B2E,0x5FFB,{ 0xBA,0xF6,0xB9,0xDD,0x7C,0x88,0xCE,0x4E } }; // 9AFF49D5-4B2E-5FFB-BAF6-B9DD7C88CE4E
    template <> inline constexpr guid guid_v<winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineErrorEventArgs>{ 0x6EA00545,0xD700,0x5174,{ 0xB6,0xB2,0xE6,0x4A,0x60,0x25,0xDD,0x86 } }; // 6EA00545-D700-5174-B6B2-E64A6025DD86
    template <> inline constexpr guid guid_v<winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineErrorEventArgsFactory>{ 0xE7FCCE98,0xC8C1,0x5808,{ 0x97,0xC1,0x7E,0x15,0x0A,0x09,0x4B,0x12 } }; // E7FCCE98-C8C1-5808-97C1-7E150A094B12
    template <> inline constexpr guid guid_v<winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineSizeChangedEventArgs>{ 0x4D50BAB2,0xF7A8,0x5E6D,{ 0x8E,0x5B,0x9A,0x44,0xE7,0x1B,0x5B,0xEB } }; // 4D50BAB2-F7A8-5E6D-8E5B-9A44E71B5BEB
    template <> inline constexpr guid guid_v<winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineSizeChangedEventArgsFactory>{ 0x6D3CB95C,0x6CCB,0x513F,{ 0xA4,0xF3,0x1B,0x1C,0xBE,0xB2,0x0A,0x30 } }; // 6D3CB95C-6CCB-513F-A4F3-1B1CBEB20A30
    template <> inline constexpr guid guid_v<winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineStateChangedEventArgs>{ 0x842ED4BC,0x5192,0x516B,{ 0xBA,0x39,0xD6,0xEA,0x69,0x0A,0x5D,0xB5 } }; // 842ED4BC-5192-516B-BA39-D6EA690A5DB5
    template <> inline constexpr guid guid_v<winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineStateChangedEventArgsFactory>{ 0xAE97C6FB,0x745F,0x52F5,{ 0xBA,0xD4,0xD9,0xA2,0xA3,0x10,0x10,0xE5 } }; // AE97C6FB-745F-52F5-BAD4-D9A2A31010E5
    template <> inline constexpr guid guid_v<winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineTimeChangedEventArgs>{ 0xACBFC471,0x7914,0x5C50,{ 0xB6,0x46,0x65,0x4B,0x58,0x65,0x80,0x09 } }; // ACBFC471-7914-5C50-B646-654B58658009
    template <> inline constexpr guid guid_v<winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineTimeChangedEventArgsFactory>{ 0xDBACD624,0x9FD9,0x52E2,{ 0x96,0x92,0x97,0x32,0x3E,0xB5,0xAF,0x9B } }; // DBACD624-9FD9-52E2-9692-97323EB5AF9B
    template <> inline constexpr guid guid_v<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyDrmConfiguration>{ 0xF047B6A3,0xE027,0x5B7F,{ 0xB2,0x4B,0xA6,0x57,0x2A,0x45,0xD0,0xA8 } }; // F047B6A3-E027-5B7F-B24B-A6572A45D0A8
    template <> inline constexpr guid guid_v<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyMediaEngine>{ 0x82D97C52,0xA539,0x5749,{ 0xA0,0xF0,0x9A,0xEB,0x53,0x76,0x9D,0xCE } }; // 82D97C52-A539-5749-A0F0-9AEB53769DCE
    template <> struct default_interface<winrt::CommunityToolkit::Maui::Media::WinRT::DrmLicenseAcquiredEventArgs>{ using type = winrt::CommunityToolkit::Maui::Media::WinRT::IDrmLicenseAcquiredEventArgs; };
    template <> struct default_interface<winrt::CommunityToolkit::Maui::Media::WinRT::MediaEngineErrorEventArgs>{ using type = winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineErrorEventArgs; };
    template <> struct default_interface<winrt::CommunityToolkit::Maui::Media::WinRT::MediaEngineSizeChangedEventArgs>{ using type = winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineSizeChangedEventArgs; };
    template <> struct default_interface<winrt::CommunityToolkit::Maui::Media::WinRT::MediaEngineStateChangedEventArgs>{ using type = winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineStateChangedEventArgs; };
    template <> struct default_interface<winrt::CommunityToolkit::Maui::Media::WinRT::MediaEngineTimeChangedEventArgs>{ using type = winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineTimeChangedEventArgs; };
    template <> struct default_interface<winrt::CommunityToolkit::Maui::Media::WinRT::PlayReadyDrmConfiguration>{ using type = winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyDrmConfiguration; };
    template <> struct default_interface<winrt::CommunityToolkit::Maui::Media::WinRT::PlayReadyMediaEngine>{ using type = winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyMediaEngine; };
    template <> struct abi<winrt::CommunityToolkit::Maui::Media::WinRT::IDrmLicenseAcquiredEventArgs>
    {
        struct WINRT_IMPL_ABI_DECL type : inspectable_abi
        {
            virtual std::int32_t __stdcall get_Success(bool*) noexcept = 0;
            virtual std::int32_t __stdcall get_ErrorMessage(void**) noexcept = 0;
        };
    };
    template <> struct abi<winrt::CommunityToolkit::Maui::Media::WinRT::IDrmLicenseAcquiredEventArgsFactory>
    {
        struct WINRT_IMPL_ABI_DECL type : inspectable_abi
        {
            virtual std::int32_t __stdcall CreateInstance(bool, void*, void**) noexcept = 0;
        };
    };
    template <> struct abi<winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineErrorEventArgs>
    {
        struct WINRT_IMPL_ABI_DECL type : inspectable_abi
        {
            virtual std::int32_t __stdcall get_ErrorCode(std::int32_t*) noexcept = 0;
            virtual std::int32_t __stdcall get_ErrorMessage(void**) noexcept = 0;
        };
    };
    template <> struct abi<winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineErrorEventArgsFactory>
    {
        struct WINRT_IMPL_ABI_DECL type : inspectable_abi
        {
            virtual std::int32_t __stdcall CreateInstance(std::int32_t, void*, void**) noexcept = 0;
        };
    };
    template <> struct abi<winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineSizeChangedEventArgs>
    {
        struct WINRT_IMPL_ABI_DECL type : inspectable_abi
        {
            virtual std::int32_t __stdcall get_Width(std::uint32_t*) noexcept = 0;
            virtual std::int32_t __stdcall get_Height(std::uint32_t*) noexcept = 0;
        };
    };
    template <> struct abi<winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineSizeChangedEventArgsFactory>
    {
        struct WINRT_IMPL_ABI_DECL type : inspectable_abi
        {
            virtual std::int32_t __stdcall CreateInstance(std::uint32_t, std::uint32_t, void**) noexcept = 0;
        };
    };
    template <> struct abi<winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineStateChangedEventArgs>
    {
        struct WINRT_IMPL_ABI_DECL type : inspectable_abi
        {
            virtual std::int32_t __stdcall get_OldState(std::int32_t*) noexcept = 0;
            virtual std::int32_t __stdcall get_NewState(std::int32_t*) noexcept = 0;
        };
    };
    template <> struct abi<winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineStateChangedEventArgsFactory>
    {
        struct WINRT_IMPL_ABI_DECL type : inspectable_abi
        {
            virtual std::int32_t __stdcall CreateInstance(std::int32_t, std::int32_t, void**) noexcept = 0;
        };
    };
    template <> struct abi<winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineTimeChangedEventArgs>
    {
        struct WINRT_IMPL_ABI_DECL type : inspectable_abi
        {
            virtual std::int32_t __stdcall get_PositionSeconds(double*) noexcept = 0;
            virtual std::int32_t __stdcall get_DurationSeconds(double*) noexcept = 0;
        };
    };
    template <> struct abi<winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineTimeChangedEventArgsFactory>
    {
        struct WINRT_IMPL_ABI_DECL type : inspectable_abi
        {
            virtual std::int32_t __stdcall CreateInstance(double, double, void**) noexcept = 0;
        };
    };
    template <> struct abi<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyDrmConfiguration>
    {
        struct WINRT_IMPL_ABI_DECL type : inspectable_abi
        {
            virtual std::int32_t __stdcall get_LicenseServerUrl(void**) noexcept = 0;
            virtual std::int32_t __stdcall put_LicenseServerUrl(void*) noexcept = 0;
            virtual std::int32_t __stdcall get_CustomHeaders(void**) noexcept = 0;
            virtual std::int32_t __stdcall put_CustomHeaders(void*) noexcept = 0;
        };
    };
    template <> struct abi<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyMediaEngine>
    {
        struct WINRT_IMPL_ABI_DECL type : inspectable_abi
        {
            virtual std::int32_t __stdcall Initialize(std::int64_t) noexcept = 0;
            virtual std::int32_t __stdcall SetSource(void*, void*) noexcept = 0;
            virtual std::int32_t __stdcall SetSourceFromManifestBytes(void*, void*, void*) noexcept = 0;
            virtual std::int32_t __stdcall TestCdmGenerateRequest(void*, void*, void*, void*, void**) noexcept = 0;
            virtual std::int32_t __stdcall Play() noexcept = 0;
            virtual std::int32_t __stdcall Pause() noexcept = 0;
            virtual std::int32_t __stdcall Seek(double) noexcept = 0;
            virtual std::int32_t __stdcall SetVolume(double) noexcept = 0;
            virtual std::int32_t __stdcall SetMuted(bool) noexcept = 0;
            virtual std::int32_t __stdcall SetPlaybackRate(double) noexcept = 0;
            virtual std::int32_t __stdcall SetLooping(bool) noexcept = 0;
            virtual std::int32_t __stdcall SetStretch(std::int32_t) noexcept = 0;
            virtual std::int32_t __stdcall ResizeSwapChain(std::uint32_t, std::uint32_t) noexcept = 0;
            virtual std::int32_t __stdcall Close() noexcept = 0;
            virtual std::int32_t __stdcall get_CurrentPositionSeconds(double*) noexcept = 0;
            virtual std::int32_t __stdcall get_DurationSeconds(double*) noexcept = 0;
            virtual std::int32_t __stdcall get_NaturalVideoWidth(std::uint32_t*) noexcept = 0;
            virtual std::int32_t __stdcall get_NaturalVideoHeight(std::uint32_t*) noexcept = 0;
            virtual std::int32_t __stdcall get_IsBuffering(bool*) noexcept = 0;
            virtual std::int32_t __stdcall add_MediaOpened(void*, winrt::event_token*) noexcept = 0;
            virtual std::int32_t __stdcall remove_MediaOpened(winrt::event_token) noexcept = 0;
            virtual std::int32_t __stdcall add_MediaFailed(void*, winrt::event_token*) noexcept = 0;
            virtual std::int32_t __stdcall remove_MediaFailed(winrt::event_token) noexcept = 0;
            virtual std::int32_t __stdcall add_MediaEnded(void*, winrt::event_token*) noexcept = 0;
            virtual std::int32_t __stdcall remove_MediaEnded(winrt::event_token) noexcept = 0;
            virtual std::int32_t __stdcall add_TimeChanged(void*, winrt::event_token*) noexcept = 0;
            virtual std::int32_t __stdcall remove_TimeChanged(winrt::event_token) noexcept = 0;
            virtual std::int32_t __stdcall add_BufferingChanged(void*, winrt::event_token*) noexcept = 0;
            virtual std::int32_t __stdcall remove_BufferingChanged(winrt::event_token) noexcept = 0;
            virtual std::int32_t __stdcall add_SizeChanged(void*, winrt::event_token*) noexcept = 0;
            virtual std::int32_t __stdcall remove_SizeChanged(winrt::event_token) noexcept = 0;
            virtual std::int32_t __stdcall add_LicenseAcquired(void*, winrt::event_token*) noexcept = 0;
            virtual std::int32_t __stdcall remove_LicenseAcquired(winrt::event_token) noexcept = 0;
            virtual std::int32_t __stdcall add_StateChanged(void*, winrt::event_token*) noexcept = 0;
            virtual std::int32_t __stdcall remove_StateChanged(winrt::event_token) noexcept = 0;
        };
    };
    template <typename D>
    struct consume_CommunityToolkit_Maui_Media_WinRT_IDrmLicenseAcquiredEventArgs
    {
        [[nodiscard]] auto Success() const;
        [[nodiscard]] auto ErrorMessage() const;
    };
    template <> struct consume<winrt::CommunityToolkit::Maui::Media::WinRT::IDrmLicenseAcquiredEventArgs>
    {
        template <typename D> using type = consume_CommunityToolkit_Maui_Media_WinRT_IDrmLicenseAcquiredEventArgs<D>;
    };
    template <typename D>
    struct consume_CommunityToolkit_Maui_Media_WinRT_IDrmLicenseAcquiredEventArgsFactory
    {
        auto CreateInstance(bool success, param::hstring const& errorMessage) const;
    };
    template <> struct consume<winrt::CommunityToolkit::Maui::Media::WinRT::IDrmLicenseAcquiredEventArgsFactory>
    {
        template <typename D> using type = consume_CommunityToolkit_Maui_Media_WinRT_IDrmLicenseAcquiredEventArgsFactory<D>;
    };
    template <typename D>
    struct consume_CommunityToolkit_Maui_Media_WinRT_IMediaEngineErrorEventArgs
    {
        [[nodiscard]] auto ErrorCode() const;
        [[nodiscard]] auto ErrorMessage() const;
    };
    template <> struct consume<winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineErrorEventArgs>
    {
        template <typename D> using type = consume_CommunityToolkit_Maui_Media_WinRT_IMediaEngineErrorEventArgs<D>;
    };
    template <typename D>
    struct consume_CommunityToolkit_Maui_Media_WinRT_IMediaEngineErrorEventArgsFactory
    {
        auto CreateInstance(std::int32_t errorCode, param::hstring const& errorMessage) const;
    };
    template <> struct consume<winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineErrorEventArgsFactory>
    {
        template <typename D> using type = consume_CommunityToolkit_Maui_Media_WinRT_IMediaEngineErrorEventArgsFactory<D>;
    };
    template <typename D>
    struct consume_CommunityToolkit_Maui_Media_WinRT_IMediaEngineSizeChangedEventArgs
    {
        [[nodiscard]] auto Width() const;
        [[nodiscard]] auto Height() const;
    };
    template <> struct consume<winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineSizeChangedEventArgs>
    {
        template <typename D> using type = consume_CommunityToolkit_Maui_Media_WinRT_IMediaEngineSizeChangedEventArgs<D>;
    };
    template <typename D>
    struct consume_CommunityToolkit_Maui_Media_WinRT_IMediaEngineSizeChangedEventArgsFactory
    {
        auto CreateInstance(std::uint32_t width, std::uint32_t height) const;
    };
    template <> struct consume<winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineSizeChangedEventArgsFactory>
    {
        template <typename D> using type = consume_CommunityToolkit_Maui_Media_WinRT_IMediaEngineSizeChangedEventArgsFactory<D>;
    };
    template <typename D>
    struct consume_CommunityToolkit_Maui_Media_WinRT_IMediaEngineStateChangedEventArgs
    {
        [[nodiscard]] auto OldState() const;
        [[nodiscard]] auto NewState() const;
    };
    template <> struct consume<winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineStateChangedEventArgs>
    {
        template <typename D> using type = consume_CommunityToolkit_Maui_Media_WinRT_IMediaEngineStateChangedEventArgs<D>;
    };
    template <typename D>
    struct consume_CommunityToolkit_Maui_Media_WinRT_IMediaEngineStateChangedEventArgsFactory
    {
        auto CreateInstance(std::int32_t oldState, std::int32_t newState) const;
    };
    template <> struct consume<winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineStateChangedEventArgsFactory>
    {
        template <typename D> using type = consume_CommunityToolkit_Maui_Media_WinRT_IMediaEngineStateChangedEventArgsFactory<D>;
    };
    template <typename D>
    struct consume_CommunityToolkit_Maui_Media_WinRT_IMediaEngineTimeChangedEventArgs
    {
        [[nodiscard]] auto PositionSeconds() const;
        [[nodiscard]] auto DurationSeconds() const;
    };
    template <> struct consume<winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineTimeChangedEventArgs>
    {
        template <typename D> using type = consume_CommunityToolkit_Maui_Media_WinRT_IMediaEngineTimeChangedEventArgs<D>;
    };
    template <typename D>
    struct consume_CommunityToolkit_Maui_Media_WinRT_IMediaEngineTimeChangedEventArgsFactory
    {
        auto CreateInstance(double positionSeconds, double durationSeconds) const;
    };
    template <> struct consume<winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineTimeChangedEventArgsFactory>
    {
        template <typename D> using type = consume_CommunityToolkit_Maui_Media_WinRT_IMediaEngineTimeChangedEventArgsFactory<D>;
    };
    template <typename D>
    struct consume_CommunityToolkit_Maui_Media_WinRT_IPlayReadyDrmConfiguration
    {
        [[nodiscard]] auto LicenseServerUrl() const;
        auto LicenseServerUrl(param::hstring const& value) const;
        [[nodiscard]] auto CustomHeaders() const;
        auto CustomHeaders(param::map<hstring, hstring> const& value) const;
    };
    template <> struct consume<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyDrmConfiguration>
    {
        template <typename D> using type = consume_CommunityToolkit_Maui_Media_WinRT_IPlayReadyDrmConfiguration<D>;
    };
    template <typename D>
    struct consume_CommunityToolkit_Maui_Media_WinRT_IPlayReadyMediaEngine
    {
        auto Initialize(std::int64_t swapChainPanelHandle) const;
        auto SetSource(param::hstring const& url, winrt::CommunityToolkit::Maui::Media::WinRT::PlayReadyDrmConfiguration const& drmConfig) const;
        auto SetSourceFromManifestBytes(param::vector_view<std::uint8_t> const& manifestData, param::hstring const& originalUrl, winrt::CommunityToolkit::Maui::Media::WinRT::PlayReadyDrmConfiguration const& drmConfig) const;
        auto TestCdmGenerateRequest(param::hstring const& mp4Path, param::hstring const& licenseUrl, param::hstring const& licenseHeaderName, param::hstring const& licenseHeaderValue) const;
        auto Play() const;
        auto Pause() const;
        auto Seek(double positionSeconds) const;
        auto SetVolume(double volume) const;
        auto SetMuted(bool muted) const;
        auto SetPlaybackRate(double rate) const;
        auto SetLooping(bool looping) const;
        auto SetStretch(std::int32_t stretchMode) const;
        auto ResizeSwapChain(std::uint32_t width, std::uint32_t height) const;
        auto Close() const;
        [[nodiscard]] auto CurrentPositionSeconds() const;
        [[nodiscard]] auto DurationSeconds() const;
        [[nodiscard]] auto NaturalVideoWidth() const;
        [[nodiscard]] auto NaturalVideoHeight() const;
        [[nodiscard]] auto IsBuffering() const;
        auto MediaOpened(winrt::Windows::Foundation::TypedEventHandler<winrt::CommunityToolkit::Maui::Media::WinRT::PlayReadyMediaEngine, winrt::Windows::Foundation::IInspectable> const& handler) const;
        using MediaOpened_revoker = impl::event_revoker<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyMediaEngine, &impl::abi_t<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyMediaEngine>::remove_MediaOpened>;
        [[nodiscard]] auto MediaOpened(auto_revoke_t, winrt::Windows::Foundation::TypedEventHandler<winrt::CommunityToolkit::Maui::Media::WinRT::PlayReadyMediaEngine, winrt::Windows::Foundation::IInspectable> const& handler) const;
        auto MediaOpened(winrt::event_token const& token) const noexcept;
        auto MediaFailed(winrt::Windows::Foundation::TypedEventHandler<winrt::CommunityToolkit::Maui::Media::WinRT::PlayReadyMediaEngine, winrt::CommunityToolkit::Maui::Media::WinRT::MediaEngineErrorEventArgs> const& handler) const;
        using MediaFailed_revoker = impl::event_revoker<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyMediaEngine, &impl::abi_t<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyMediaEngine>::remove_MediaFailed>;
        [[nodiscard]] auto MediaFailed(auto_revoke_t, winrt::Windows::Foundation::TypedEventHandler<winrt::CommunityToolkit::Maui::Media::WinRT::PlayReadyMediaEngine, winrt::CommunityToolkit::Maui::Media::WinRT::MediaEngineErrorEventArgs> const& handler) const;
        auto MediaFailed(winrt::event_token const& token) const noexcept;
        auto MediaEnded(winrt::Windows::Foundation::TypedEventHandler<winrt::CommunityToolkit::Maui::Media::WinRT::PlayReadyMediaEngine, winrt::Windows::Foundation::IInspectable> const& handler) const;
        using MediaEnded_revoker = impl::event_revoker<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyMediaEngine, &impl::abi_t<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyMediaEngine>::remove_MediaEnded>;
        [[nodiscard]] auto MediaEnded(auto_revoke_t, winrt::Windows::Foundation::TypedEventHandler<winrt::CommunityToolkit::Maui::Media::WinRT::PlayReadyMediaEngine, winrt::Windows::Foundation::IInspectable> const& handler) const;
        auto MediaEnded(winrt::event_token const& token) const noexcept;
        auto TimeChanged(winrt::Windows::Foundation::TypedEventHandler<winrt::CommunityToolkit::Maui::Media::WinRT::PlayReadyMediaEngine, winrt::CommunityToolkit::Maui::Media::WinRT::MediaEngineTimeChangedEventArgs> const& handler) const;
        using TimeChanged_revoker = impl::event_revoker<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyMediaEngine, &impl::abi_t<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyMediaEngine>::remove_TimeChanged>;
        [[nodiscard]] auto TimeChanged(auto_revoke_t, winrt::Windows::Foundation::TypedEventHandler<winrt::CommunityToolkit::Maui::Media::WinRT::PlayReadyMediaEngine, winrt::CommunityToolkit::Maui::Media::WinRT::MediaEngineTimeChangedEventArgs> const& handler) const;
        auto TimeChanged(winrt::event_token const& token) const noexcept;
        auto BufferingChanged(winrt::Windows::Foundation::TypedEventHandler<winrt::CommunityToolkit::Maui::Media::WinRT::PlayReadyMediaEngine, bool> const& handler) const;
        using BufferingChanged_revoker = impl::event_revoker<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyMediaEngine, &impl::abi_t<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyMediaEngine>::remove_BufferingChanged>;
        [[nodiscard]] auto BufferingChanged(auto_revoke_t, winrt::Windows::Foundation::TypedEventHandler<winrt::CommunityToolkit::Maui::Media::WinRT::PlayReadyMediaEngine, bool> const& handler) const;
        auto BufferingChanged(winrt::event_token const& token) const noexcept;
        auto SizeChanged(winrt::Windows::Foundation::TypedEventHandler<winrt::CommunityToolkit::Maui::Media::WinRT::PlayReadyMediaEngine, winrt::CommunityToolkit::Maui::Media::WinRT::MediaEngineSizeChangedEventArgs> const& handler) const;
        using SizeChanged_revoker = impl::event_revoker<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyMediaEngine, &impl::abi_t<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyMediaEngine>::remove_SizeChanged>;
        [[nodiscard]] auto SizeChanged(auto_revoke_t, winrt::Windows::Foundation::TypedEventHandler<winrt::CommunityToolkit::Maui::Media::WinRT::PlayReadyMediaEngine, winrt::CommunityToolkit::Maui::Media::WinRT::MediaEngineSizeChangedEventArgs> const& handler) const;
        auto SizeChanged(winrt::event_token const& token) const noexcept;
        auto LicenseAcquired(winrt::Windows::Foundation::TypedEventHandler<winrt::CommunityToolkit::Maui::Media::WinRT::PlayReadyMediaEngine, winrt::CommunityToolkit::Maui::Media::WinRT::DrmLicenseAcquiredEventArgs> const& handler) const;
        using LicenseAcquired_revoker = impl::event_revoker<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyMediaEngine, &impl::abi_t<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyMediaEngine>::remove_LicenseAcquired>;
        [[nodiscard]] auto LicenseAcquired(auto_revoke_t, winrt::Windows::Foundation::TypedEventHandler<winrt::CommunityToolkit::Maui::Media::WinRT::PlayReadyMediaEngine, winrt::CommunityToolkit::Maui::Media::WinRT::DrmLicenseAcquiredEventArgs> const& handler) const;
        auto LicenseAcquired(winrt::event_token const& token) const noexcept;
        auto StateChanged(winrt::Windows::Foundation::TypedEventHandler<winrt::CommunityToolkit::Maui::Media::WinRT::PlayReadyMediaEngine, winrt::CommunityToolkit::Maui::Media::WinRT::MediaEngineStateChangedEventArgs> const& handler) const;
        using StateChanged_revoker = impl::event_revoker<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyMediaEngine, &impl::abi_t<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyMediaEngine>::remove_StateChanged>;
        [[nodiscard]] auto StateChanged(auto_revoke_t, winrt::Windows::Foundation::TypedEventHandler<winrt::CommunityToolkit::Maui::Media::WinRT::PlayReadyMediaEngine, winrt::CommunityToolkit::Maui::Media::WinRT::MediaEngineStateChangedEventArgs> const& handler) const;
        auto StateChanged(winrt::event_token const& token) const noexcept;
    };
    template <> struct consume<winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyMediaEngine>
    {
        template <typename D> using type = consume_CommunityToolkit_Maui_Media_WinRT_IPlayReadyMediaEngine<D>;
    };
}
#endif
