// WARNING: Please don't edit this file. It was generated by C++/WinRT v3.0.260715.1

#pragma once
#ifndef WINRT_CommunityToolkit_Maui_Media_WinRT_2_H
#define WINRT_CommunityToolkit_Maui_Media_WinRT_2_H
#ifndef WINRT_IMPL_BUILD_MODULE
#include "winrt/impl/CommunityToolkit.Maui.Media.WinRT.1.h"
#endif // WINRT_IMPL_BUILD_MODULE
WINRT_EXPORT namespace winrt::CommunityToolkit::Maui::Media::WinRT
{
    struct WINRT_IMPL_EMPTY_BASES DrmLicenseAcquiredEventArgs : winrt::CommunityToolkit::Maui::Media::WinRT::IDrmLicenseAcquiredEventArgs
    {
        DrmLicenseAcquiredEventArgs(std::nullptr_t) noexcept {}
        DrmLicenseAcquiredEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::CommunityToolkit::Maui::Media::WinRT::IDrmLicenseAcquiredEventArgs(ptr, take_ownership_from_abi) {}
        DrmLicenseAcquiredEventArgs(bool success, param::hstring const& errorMessage);
    };
    struct WINRT_IMPL_EMPTY_BASES MediaEngineErrorEventArgs : winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineErrorEventArgs
    {
        MediaEngineErrorEventArgs(std::nullptr_t) noexcept {}
        MediaEngineErrorEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineErrorEventArgs(ptr, take_ownership_from_abi) {}
        MediaEngineErrorEventArgs(std::int32_t errorCode, param::hstring const& errorMessage);
    };
    struct WINRT_IMPL_EMPTY_BASES MediaEngineSizeChangedEventArgs : winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineSizeChangedEventArgs
    {
        MediaEngineSizeChangedEventArgs(std::nullptr_t) noexcept {}
        MediaEngineSizeChangedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineSizeChangedEventArgs(ptr, take_ownership_from_abi) {}
        MediaEngineSizeChangedEventArgs(std::uint32_t width, std::uint32_t height);
    };
    struct WINRT_IMPL_EMPTY_BASES MediaEngineStateChangedEventArgs : winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineStateChangedEventArgs
    {
        MediaEngineStateChangedEventArgs(std::nullptr_t) noexcept {}
        MediaEngineStateChangedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineStateChangedEventArgs(ptr, take_ownership_from_abi) {}
        MediaEngineStateChangedEventArgs(std::int32_t oldState, std::int32_t newState);
    };
    struct WINRT_IMPL_EMPTY_BASES MediaEngineTimeChangedEventArgs : winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineTimeChangedEventArgs
    {
        MediaEngineTimeChangedEventArgs(std::nullptr_t) noexcept {}
        MediaEngineTimeChangedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::CommunityToolkit::Maui::Media::WinRT::IMediaEngineTimeChangedEventArgs(ptr, take_ownership_from_abi) {}
        MediaEngineTimeChangedEventArgs(double positionSeconds, double durationSeconds);
    };
    struct WINRT_IMPL_EMPTY_BASES PlayReadyDrmConfiguration : winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyDrmConfiguration
    {
        PlayReadyDrmConfiguration(std::nullptr_t) noexcept {}
        PlayReadyDrmConfiguration(void* ptr, take_ownership_from_abi_t) noexcept : winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyDrmConfiguration(ptr, take_ownership_from_abi) {}
        PlayReadyDrmConfiguration();
    };
    struct WINRT_IMPL_EMPTY_BASES PlayReadyMediaEngine : winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyMediaEngine
    {
        PlayReadyMediaEngine(std::nullptr_t) noexcept {}
        PlayReadyMediaEngine(void* ptr, take_ownership_from_abi_t) noexcept : winrt::CommunityToolkit::Maui::Media::WinRT::IPlayReadyMediaEngine(ptr, take_ownership_from_abi) {}
        PlayReadyMediaEngine();
    };
}
#endif
