// WARNING: Please don't edit this file. It was generated by C++/WinRT v3.0.260715.1

#pragma once
#ifndef WINRT_CommunityToolkit_Maui_Media_WinRT_1_H
#define WINRT_CommunityToolkit_Maui_Media_WinRT_1_H
#ifndef WINRT_IMPL_BUILD_MODULE
#include "winrt/impl/CommunityToolkit.Maui.Media.WinRT.0.h"
#endif // WINRT_IMPL_BUILD_MODULE
WINRT_EXPORT namespace winrt::CommunityToolkit::Maui::Media::WinRT
{
    struct WINRT_IMPL_EMPTY_BASES IDrmLicenseAcquiredEventArgs :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IDrmLicenseAcquiredEventArgs>
    {
        IDrmLicenseAcquiredEventArgs(std::nullptr_t = nullptr) noexcept {}
        IDrmLicenseAcquiredEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES IDrmLicenseAcquiredEventArgsFactory :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IDrmLicenseAcquiredEventArgsFactory>
    {
        IDrmLicenseAcquiredEventArgsFactory(std::nullptr_t = nullptr) noexcept {}
        IDrmLicenseAcquiredEventArgsFactory(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES IMediaEngineErrorEventArgs :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IMediaEngineErrorEventArgs>
    {
        IMediaEngineErrorEventArgs(std::nullptr_t = nullptr) noexcept {}
        IMediaEngineErrorEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES IMediaEngineErrorEventArgsFactory :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IMediaEngineErrorEventArgsFactory>
    {
        IMediaEngineErrorEventArgsFactory(std::nullptr_t = nullptr) noexcept {}
        IMediaEngineErrorEventArgsFactory(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES IMediaEngineSizeChangedEventArgs :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IMediaEngineSizeChangedEventArgs>
    {
        IMediaEngineSizeChangedEventArgs(std::nullptr_t = nullptr) noexcept {}
        IMediaEngineSizeChangedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES IMediaEngineSizeChangedEventArgsFactory :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IMediaEngineSizeChangedEventArgsFactory>
    {
        IMediaEngineSizeChangedEventArgsFactory(std::nullptr_t = nullptr) noexcept {}
        IMediaEngineSizeChangedEventArgsFactory(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES IMediaEngineStateChangedEventArgs :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IMediaEngineStateChangedEventArgs>
    {
        IMediaEngineStateChangedEventArgs(std::nullptr_t = nullptr) noexcept {}
        IMediaEngineStateChangedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES IMediaEngineStateChangedEventArgsFactory :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IMediaEngineStateChangedEventArgsFactory>
    {
        IMediaEngineStateChangedEventArgsFactory(std::nullptr_t = nullptr) noexcept {}
        IMediaEngineStateChangedEventArgsFactory(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES IMediaEngineTimeChangedEventArgs :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IMediaEngineTimeChangedEventArgs>
    {
        IMediaEngineTimeChangedEventArgs(std::nullptr_t = nullptr) noexcept {}
        IMediaEngineTimeChangedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES IMediaEngineTimeChangedEventArgsFactory :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IMediaEngineTimeChangedEventArgsFactory>
    {
        IMediaEngineTimeChangedEventArgsFactory(std::nullptr_t = nullptr) noexcept {}
        IMediaEngineTimeChangedEventArgsFactory(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES IPlayReadyDrmConfiguration :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IPlayReadyDrmConfiguration>
    {
        IPlayReadyDrmConfiguration(std::nullptr_t = nullptr) noexcept {}
        IPlayReadyDrmConfiguration(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES IPlayReadyMediaEngine :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IPlayReadyMediaEngine>
    {
        IPlayReadyMediaEngine(std::nullptr_t = nullptr) noexcept {}
        IPlayReadyMediaEngine(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
}
#endif
